/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edent.view.utils;

import edent.model.Tooth;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Stepan Tesar
 */
public class ToothPanel extends javax.swing.JPanel {

    private static final Font MARK_FONT = new Font("Arial", 0, 18);
    private JLabel braceLabel;
    private JLabel milkLabel;
    private JLabel toothStateLabel;
    private JLabel gumStateLabel;
    private Tooth t;
    private Color bg;
    private boolean selected = false;

    /**
     * Creates new form ToothTop
     */
    public ToothPanel(Tooth t) {
        initComponents();
        this.t = t;
        this.myInit();

        this.setOpaque(true);
        if ((t.getPosition()) % 2 == 0) {
            this.setBackground(Color.white);
        } else {
            this.setBackground(Color.gray.brighter());
        }
        this.bg = this.getBackground();
    }

    private void myInit() {
        this.panelImg.removeAll();

        int pos = t.getPosition();
        boolean left = t.isLeftSide();
        boolean top = t.isTopFloor();
//        String toothMark = t.getState() != null ? t.getState().getMark() : " ";
//        String gumMark = t.getGum().getState() != null ? t.getGum().getState().getMark() : " ";
//        String braceMark = t.isBraced() ? "-B-" : " ";
//        String milkMark = t.isMilk() ? " M " : " ";
        String pic = pos + (top ? "top" : "bot") + (left ? "L" : "");

        JLabel img = new JLabel(new ImageIcon(getClass().getResource("/edent/view/utils/teeth/" + pic + ".png")));
        img.setPreferredSize(new Dimension(60, 130));
        img.setLayout(new BoxLayout(img, BoxLayout.Y_AXIS));

        JLabel p = new JLabel(" ");
        braceLabel = new JLabel(" ");
        milkLabel = new JLabel(" ");

        braceLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        braceLabel.setFont(MARK_FONT);
        braceLabel.setBorder(new EmptyBorder(2, 2, 2, 2));
        milkLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        milkLabel.setFont(MARK_FONT);
        milkLabel.setBorder(new EmptyBorder(2, 2, 2, 2));

        toothStateLabel = new JLabel(" ");
        toothStateLabel.setFont(MARK_FONT);
        gumStateLabel = new JLabel(" ");
        toothStateLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        gumStateLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        gumStateLabel.setFont(MARK_FONT);
        gumStateLabel.setOpaque(true);
        gumStateLabel.setBackground(new Color(255,204,204));
        img.setAlignmentX(Component.CENTER_ALIGNMENT);

        if (top) {
            img.add(p);
            p = new JLabel(" ");
            img.add(p);
            p = new JLabel(" ");
            img.add(p);
            img.add(milkLabel);
            p = new JLabel(" ");
            img.add(p);
            img.add(braceLabel);
            
            this.panelImg.add(gumStateLabel);
            this.panelImg.add(toothStateLabel);
            this.panelImg.add(img);
        } else {
            img.add(p);
            p = new JLabel(" ");
            img.add(p);
            img.add(braceLabel);
            p = new JLabel(" ");
            img.add(p);
            img.add(milkLabel);

            this.panelImg.add(img);
            this.panelImg.add(toothStateLabel);
            this.panelImg.add(gumStateLabel);
        }
        this.refreshMarks();
        this.panelImg.validate();
        this.panelImg.repaint();
        this.revalidate();
    }

    public void refreshMarks() {
        String toothMark = t.getState() != null ? t.getState().getMark() : " ";
        String gumMark = t.getGum().getState() != null ? t.getGum().getState().getMark() : " ";
        String braceMark = t.isBraced() ? "-B-" : " ";
        String milkMark = t.isMilk() ? " M " : " ";

        braceLabel.setText(" " + braceMark + " ");
        milkLabel.setText(" " + milkMark + " ");
        toothStateLabel.setText(" " + toothMark + " ");
        gumStateLabel.setText(" " + gumMark + " ");
    }

    public Color getBg() {
        return bg;
    }

    public Tooth getTooth() {
        return t;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        if (selected) {
            this.setBackground(new Color(0, 162, 232));
        } else {
            this.setBackground(this.bg);
        }
        this.selected = selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImg = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(42, 120));

        panelImg.setBackground(new java.awt.Color(255, 255, 255));
        panelImg.setMinimumSize(new java.awt.Dimension(60, 150));
        panelImg.setOpaque(false);
        panelImg.setPreferredSize(new java.awt.Dimension(60, 150));
        panelImg.setLayout(new javax.swing.BoxLayout(panelImg, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelImg;
    // End of variables declaration//GEN-END:variables
}
