//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:cz-mzcr:ns:dasta:ds4:ds_type")
package mzcr.cz.ns.dasta.ds4.ds_type;
