//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for projekceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="projekceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PA"/>
 *     &lt;enumeration value="LAT"/>
 *     &lt;enumeration value="LSJ"/>
 *     &lt;enumeration value="AP"/>
 *     &lt;enumeration value="Periapical"/>
 *     &lt;enumeration value="CC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "projekceType")
@XmlEnum
public enum ProjekceType {

    PA("PA"),
    LAT("LAT"),
    LSJ("LSJ"),
    AP("AP"),
    @XmlEnumValue("Periapical")
    PERIAPICAL("Periapical"),
    CC("CC");
    private final String value;

    ProjekceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProjekceType fromValue(String v) {
        for (ProjekceType c: ProjekceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
