//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_cistype;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NCMPZZM.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NCMPZZM">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VYTER "/>
 *     &lt;enumeration value="STER "/>
 *     &lt;enumeration value="PUNKCE"/>
 *     &lt;enumeration value="ODSATI"/>
 *     &lt;enumeration value="LAVAZ"/>
 *     &lt;enumeration value="PSB"/>
 *     &lt;enumeration value="SESKRAB"/>
 *     &lt;enumeration value="BIOPSIE"/>
 *     &lt;enumeration value="EXCIZE "/>
 *     &lt;enumeration value="PUNSUPRA"/>
 *     &lt;enumeration value="CEVKOVANI"/>
 *     &lt;enumeration value="STRPROUD"/>
 *     &lt;enumeration value="ASPTRACH"/>
 *     &lt;enumeration value="NATERPOD"/>
 *     &lt;enumeration value="EXPEKTOR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NCMPZZM", namespace = "urn:cz-mzcr:ns:dasta:ds4:ds_cistype")
@XmlEnum
public enum NCMPZZM {

    @XmlEnumValue("VYTER ")
    VYTER("VYTER "),
    @XmlEnumValue("STER ")
    STER("STER "),
    PUNKCE("PUNKCE"),
    ODSATI("ODSATI"),
    LAVAZ("LAVAZ"),
    PSB("PSB"),
    SESKRAB("SESKRAB"),
    BIOPSIE("BIOPSIE"),
    @XmlEnumValue("EXCIZE ")
    EXCIZE("EXCIZE "),
    PUNSUPRA("PUNSUPRA"),
    CEVKOVANI("CEVKOVANI"),
    STRPROUD("STRPROUD"),
    ASPTRACH("ASPTRACH"),
    NATERPOD("NATERPOD"),
    EXPEKTOR("EXPEKTOR");
    private final String value;

    NCMPZZM(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NCMPZZM fromValue(String v) {
        for (NCMPZZM c: NCMPZZM.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
