//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_cistype;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vyznObsahSdeleni.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="vyznObsahSdeleni">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UNR"/>
 *     &lt;enumeration value="UNM"/>
 *     &lt;enumeration value="ULR"/>
 *     &lt;enumeration value="ULM"/>
 *     &lt;enumeration value="JXP"/>
 *     &lt;enumeration value="JXF"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "vyznObsahSdeleni", namespace = "urn:cz-mzcr:ns:dasta:ds4:ds_cistype")
@XmlEnum
public enum VyznObsahSdeleni {

    UNR,
    UNM,
    ULR,
    ULM,
    JXP,
    JXF;

    public String value() {
        return name();
    }

    public static VyznObsahSdeleni fromValue(String v) {
        return valueOf(v);
    }

}
