//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_dasta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.GarantDatType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zdroj_is" type="{urn:cz-mzcr:ns:dasta:ds4:ds_dasta}zdroj_isType"/>
 *         &lt;element name="pm" type="{urn:cz-mzcr:ns:dasta:ds4:ds_dasta}pmType"/>
 *         &lt;element name="garant_dat" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}garant_datType" minOccurs="0"/>
 *         &lt;element name="is" type="{urn:cz-mzcr:ns:dasta:ds4:ds_dasta}isType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dastaAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id_soubor" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str40" />
 *       &lt;attribute name="verze_ds" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}verzeDsType" />
 *       &lt;attribute name="verze_nclp" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}verzeDsType" />
 *       &lt;attribute name="bin_priloha" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="B"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ur" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="R"/>
 *             &lt;enumeration value="S"/>
 *             &lt;enumeration value="U"/>
 *             &lt;enumeration value="B"/>
 *             &lt;enumeration value="C"/>
 *             &lt;enumeration value="H"/>
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="typ_odesm" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="ozn_soub" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="potvrzeni">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="P"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dat_vb" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_dtsType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ds", propOrder = {
    "zdrojIs",
    "pm",
    "garantDat",
    "is",
    "dastaAny"
})
@XmlRootElement(name = "dasta")
public class Dasta {

    @XmlElement(name = "zdroj_is", required = true)
    protected ZdrojIsType zdrojIs;
    @XmlElement(required = true)
    protected PmType pm;
    @XmlElement(name = "garant_dat")
    protected GarantDatType garantDat;
    @XmlElement(name = "is", required = true)
    protected List<IsType> is;
    protected AnyType dastaAny;
    @XmlAttribute(name = "id_soubor", required = true)
    protected String idSoubor;
    @XmlAttribute(name = "verze_ds", required = true)
    protected String verzeDs;
    @XmlAttribute(name = "verze_nclp", required = true)
    protected String verzeNclp;
    @XmlAttribute(name = "bin_priloha", required = true)
    protected String binPriloha;
    @XmlAttribute(required = true)
    protected String ur;
    @XmlAttribute(name = "typ_odesm", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String typOdesm;
    @XmlAttribute(name = "ozn_soub", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String oznSoub;
    @XmlAttribute
    protected String potvrzeni;
    @XmlAttribute(name = "dat_vb", required = true)
    protected XMLGregorianCalendar datVb;

    /**
     * Gets the value of the zdrojIs property.
     * 
     * @return
     *     possible object is
     *     {@link ZdrojIsType }
     *     
     */
    public ZdrojIsType getZdrojIs() {
        return zdrojIs;
    }

    /**
     * Sets the value of the zdrojIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZdrojIsType }
     *     
     */
    public void setZdrojIs(ZdrojIsType value) {
        this.zdrojIs = value;
    }

    public void setIs(List<IsType> is) {
        this.is = is;
    }
        
    /**
     * Gets the value of the pm property.
     * 
     * @return
     *     possible object is
     *     {@link PmType }
     *     
     */
    public PmType getPm() {
        return pm;
    }

    /**
     * Sets the value of the pm property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmType }
     *     
     */
    public void setPm(PmType value) {
        this.pm = value;
    }

    /**
     * Gets the value of the garantDat property.
     * 
     * @return
     *     possible object is
     *     {@link GarantDatType }
     *     
     */
    public GarantDatType getGarantDat() {
        return garantDat;
    }

    /**
     * Sets the value of the garantDat property.
     * 
     * @param value
     *     allowed object is
     *     {@link GarantDatType }
     *     
     */
    public void setGarantDat(GarantDatType value) {
        this.garantDat = value;
    }

    /**
     * Gets the value of the is property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the is property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IsType }
     * 
     * 
     */
    /*public List<IsType> getIs() {
        if (is == null) {
            is = new ArrayList<IsType>();
        }
        return this.is;
    }*/

    /**
     * Gets the value of the dastaAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getDastaAny() {
        return dastaAny;
    }

    /**
     * Sets the value of the dastaAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setDastaAny(AnyType value) {
        this.dastaAny = value;
    }

    /**
     * Gets the value of the idSoubor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSoubor() {
        return idSoubor;
    }

    /**
     * Sets the value of the idSoubor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSoubor(String value) {
        this.idSoubor = value;
    }

    /**
     * Gets the value of the verzeDs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerzeDs() {
        return verzeDs;
    }

    /**
     * Sets the value of the verzeDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerzeDs(String value) {
        this.verzeDs = value;
    }

    /**
     * Gets the value of the verzeNclp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerzeNclp() {
        return verzeNclp;
    }

    /**
     * Sets the value of the verzeNclp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerzeNclp(String value) {
        this.verzeNclp = value;
    }

    /**
     * Gets the value of the binPriloha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinPriloha() {
        return binPriloha;
    }

    /**
     * Sets the value of the binPriloha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinPriloha(String value) {
        this.binPriloha = value;
    }

    /**
     * Gets the value of the ur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUr() {
        return ur;
    }

    /**
     * Sets the value of the ur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUr(String value) {
        this.ur = value;
    }

    /**
     * Gets the value of the typOdesm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypOdesm() {
        return typOdesm;
    }

    /**
     * Sets the value of the typOdesm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypOdesm(String value) {
        this.typOdesm = value;
    }

    /**
     * Gets the value of the oznSoub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOznSoub() {
        return oznSoub;
    }

    /**
     * Sets the value of the oznSoub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOznSoub(String value) {
        this.oznSoub = value;
    }

    /**
     * Gets the value of the potvrzeni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotvrzeni() {
        return potvrzeni;
    }

    /**
     * Sets the value of the potvrzeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotvrzeni(String value) {
        this.potvrzeni = value;
    }

    /**
     * Gets the value of the datVb property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatVb() {
        return datVb;
    }

    /**
     * Sets the value of the datVb property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatVb(XMLGregorianCalendar value) {
        this.datVb = value;
    }

}
