//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_dasta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for pmType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="as" type="{urn:cz-mzcr:ns:dasta:ds4:ds_dasta}asType"/>
 *         &lt;element name="a" type="{urn:cz-mzcr:ns:dasta:ds4:ds_dasta}aType" minOccurs="0"/>
 *         &lt;element name="pmAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:cz-mzcr:ns:dasta:ds4:ds_type}icisAttrGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pmType", propOrder = {
    "as",
    "a",
    "pmAny"
})
public class PmType {

    @XmlElement(required = true)
    protected AsType as;
    protected AType a;
    protected AnyType pmAny;
    @XmlAttribute
    protected String ico;
    @XmlAttribute
    protected String icz;
    @XmlAttribute
    protected String icp;
    @XmlAttribute
    protected String icl;
    @XmlAttribute
    protected String pcz;
    @XmlAttribute
    protected String oddel;

    /**
     * Gets the value of the as property.
     * 
     * @return
     *     possible object is
     *     {@link AsType }
     *     
     */
    public AsType getAs() {
        return as;
    }

    /**
     * Sets the value of the as property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsType }
     *     
     */
    public void setAs(AsType value) {
        this.as = value;
    }

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link AType }
     *     
     */
    public AType getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link AType }
     *     
     */
    public void setA(AType value) {
        this.a = value;
    }

    /**
     * Gets the value of the pmAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getPmAny() {
        return pmAny;
    }

    /**
     * Sets the value of the pmAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setPmAny(AnyType value) {
        this.pmAny = value;
    }

    /**
     * Gets the value of the ico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIco() {
        return ico;
    }

    /**
     * Sets the value of the ico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIco(String value) {
        this.ico = value;
    }

    /**
     * Gets the value of the icz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcz() {
        return icz;
    }

    /**
     * Sets the value of the icz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcz(String value) {
        this.icz = value;
    }

    /**
     * Gets the value of the icp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcp() {
        return icp;
    }

    /**
     * Sets the value of the icp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcp(String value) {
        this.icp = value;
    }

    /**
     * Gets the value of the icl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcl() {
        return icl;
    }

    /**
     * Sets the value of the icl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcl(String value) {
        this.icl = value;
    }

    /**
     * Gets the value of the pcz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcz() {
        return pcz;
    }

    /**
     * Sets the value of the pcz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcz(String value) {
        this.pcz = value;
    }

    /**
     * Gets the value of the oddel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOddel() {
        return oddel;
    }

    /**
     * Sets the value of the oddel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOddel(String value) {
        this.oddel = value;
    }

}
