//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_dasta.AType;


/**
 * <p>Java class for ahpnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ahpnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:cz-mzcr:ns:dasta:ds4:ds_dasta}a"/>
 *         &lt;element name="astat" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str2e" minOccurs="0"/>
 *         &lt;element name="dath_od" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType" minOccurs="0"/>
 *         &lt;element name="dath_do" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="acp" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str12" />
 *       &lt;attribute name="aco" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str4" />
 *       &lt;attribute name="az">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ahpnType", propOrder = {
    "a",
    "astat",
    "dathOd",
    "dathDo"
})
public class AhpnType {

    @XmlElement(namespace = "urn:cz-mzcr:ns:dasta:ds4:ds_dasta", required = true)
    protected AType a;
    protected String astat;
    @XmlElement(name = "dath_od")
    protected DathXxType dathOd;
    @XmlElement(name = "dath_do")
    protected DathXxType dathDo;
    @XmlAttribute
    protected String acp;
    @XmlAttribute
    protected String aco;
    @XmlAttribute
    protected String az;

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link AType }
     *     
     */
    public AType getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link AType }
     *     
     */
    public void setA(AType value) {
        this.a = value;
    }

    /**
     * Gets the value of the astat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAstat() {
        return astat;
    }

    /**
     * Sets the value of the astat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAstat(String value) {
        this.astat = value;
    }

    /**
     * Gets the value of the dathOd property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathOd() {
        return dathOd;
    }

    /**
     * Sets the value of the dathOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathOd(DathXxType value) {
        this.dathOd = value;
    }

    /**
     * Gets the value of the dathDo property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathDo() {
        return dathDo;
    }

    /**
     * Sets the value of the dathDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathDo(DathXxType value) {
        this.dathDo = value;
    }

    /**
     * Gets the value of the acp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcp() {
        return acp;
    }

    /**
     * Sets the value of the acp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcp(String value) {
        this.acp = value;
    }

    /**
     * Gets the value of the aco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAco() {
        return aco;
    }

    /**
     * Sets the value of the aco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAco(String value) {
        this.aco = value;
    }

    /**
     * Gets the value of the az property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAz() {
        return az;
    }

    /**
     * Sets the value of the az property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAz(String value) {
        this.az = value;
    }

}
