//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatXxType;
import mzcr.cz.ns.dasta.ds4.ds_type.GarantDatType;


/**
 * <p>Java class for anType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="anType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="garant_dat" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}garant_datType" minOccurs="0"/>
 *         &lt;element name="text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}textType"/>
 *         &lt;element name="dat_ak" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *         &lt;element name="anAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dat_ab" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anType", propOrder = {
    "garantDat",
    "text",
    "datAk",
    "anAny"
})
public class AnType {

    @XmlElement(name = "garant_dat")
    protected GarantDatType garantDat;
    @XmlElement(required = true)
    protected TextType text;
    @XmlElement(name = "dat_ak")
    protected DatXxType datAk;
    protected AnyType anAny;
    @XmlAttribute(name = "dat_ab")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datAb;

    /**
     * Gets the value of the garantDat property.
     * 
     * @return
     *     possible object is
     *     {@link GarantDatType }
     *     
     */
    public GarantDatType getGarantDat() {
        return garantDat;
    }

    /**
     * Sets the value of the garantDat property.
     * 
     * @param value
     *     allowed object is
     *     {@link GarantDatType }
     *     
     */
    public void setGarantDat(GarantDatType value) {
        this.garantDat = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setText(TextType value) {
        this.text = value;
    }

    /**
     * Gets the value of the datAk property.
     * 
     * @return
     *     possible object is
     *     {@link DatXxType }
     *     
     */
    public DatXxType getDatAk() {
        return datAk;
    }

    /**
     * Sets the value of the datAk property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatXxType }
     *     
     */
    public void setDatAk(DatXxType value) {
        this.datAk = value;
    }

    /**
     * Gets the value of the anAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getAnAny() {
        return anAny;
    }

    /**
     * Sets the value of the anAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setAnAny(AnyType value) {
        this.anAny = value;
    }

    /**
     * Gets the value of the datAb property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatAb() {
        return datAb;
    }

    /**
     * Sets the value of the datAb property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatAb(XMLGregorianCalendar value) {
        this.datAb = value;
    }

}
