//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatDuType;


/**
 * <p>Java class for auzType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="auzType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dat_du" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_duType" minOccurs="0"/>
 *         &lt;element name="auzAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="indikace" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}indikaceAUZType" />
 *       &lt;attribute name="doklad" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number2de" />
 *       &lt;attribute name="polozka" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}polozkaType" />
 *       &lt;attribute name="diag" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str5" />
 *       &lt;attribute name="kod_vykonu" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str5" />
 *       &lt;attribute name="lok_zubu" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str4" />
 *       &lt;attribute name="mnozstvi" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number8.3" />
 *       &lt;attribute name="cena" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number8d" />
 *       &lt;attribute name="kod_lab" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str4" />
 *       &lt;attribute name="sr_cito" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1" fixed="C" />
 *       &lt;attribute name="sr_nahrady" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str2" />
 *       &lt;attribute name="sr_kod_lek" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str6" />
 *       &lt;attribute name="sr_mnozstvi" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
 *       &lt;attribute name="sr_cena" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "auzType", propOrder = {
    "datDu",
    "auzAny"
})
public class AuzType {

    @XmlElement(name = "dat_du")
    protected DatDuType datDu;
    protected AnyType auzAny;
    @XmlAttribute(required = true)
    protected String indikace;
    @XmlAttribute
    protected String doklad;
    @XmlAttribute(required = true)
    protected String polozka;
    @XmlAttribute
    protected String diag;
    @XmlAttribute(name = "kod_vykonu", required = true)
    protected String kodVykonu;
    @XmlAttribute(name = "lok_zubu")
    protected String lokZubu;
    @XmlAttribute
    protected String mnozstvi;
    @XmlAttribute
    protected BigInteger cena;
    @XmlAttribute(name = "kod_lab")
    protected String kodLab;
    @XmlAttribute(name = "sr_cito")
    protected String srCito;
    @XmlAttribute(name = "sr_nahrady")
    protected String srNahrady;
    @XmlAttribute(name = "sr_kod_lek")
    protected String srKodLek;
    @XmlAttribute(name = "sr_mnozstvi")
    protected String srMnozstvi;
    @XmlAttribute(name = "sr_cena")
    protected String srCena;

    /**
     * Gets the value of the datDu property.
     * 
     * @return
     *     possible object is
     *     {@link DatDuType }
     *     
     */
    public DatDuType getDatDu() {
        return datDu;
    }

    /**
     * Sets the value of the datDu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatDuType }
     *     
     */
    public void setDatDu(DatDuType value) {
        this.datDu = value;
    }

    /**
     * Gets the value of the auzAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getAuzAny() {
        return auzAny;
    }

    /**
     * Sets the value of the auzAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setAuzAny(AnyType value) {
        this.auzAny = value;
    }

    /**
     * Gets the value of the indikace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndikace() {
        return indikace;
    }

    /**
     * Sets the value of the indikace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndikace(String value) {
        this.indikace = value;
    }

    /**
     * Gets the value of the doklad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoklad() {
        return doklad;
    }

    /**
     * Sets the value of the doklad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoklad(String value) {
        this.doklad = value;
    }

    /**
     * Gets the value of the polozka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolozka() {
        return polozka;
    }

    /**
     * Sets the value of the polozka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolozka(String value) {
        this.polozka = value;
    }

    /**
     * Gets the value of the diag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiag() {
        return diag;
    }

    /**
     * Sets the value of the diag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiag(String value) {
        this.diag = value;
    }

    /**
     * Gets the value of the kodVykonu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodVykonu() {
        return kodVykonu;
    }

    /**
     * Sets the value of the kodVykonu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodVykonu(String value) {
        this.kodVykonu = value;
    }

    /**
     * Gets the value of the lokZubu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLokZubu() {
        return lokZubu;
    }

    /**
     * Sets the value of the lokZubu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLokZubu(String value) {
        this.lokZubu = value;
    }

    /**
     * Gets the value of the mnozstvi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMnozstvi() {
        return mnozstvi;
    }

    /**
     * Sets the value of the mnozstvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMnozstvi(String value) {
        this.mnozstvi = value;
    }

    /**
     * Gets the value of the cena property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCena() {
        return cena;
    }

    /**
     * Sets the value of the cena property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCena(BigInteger value) {
        this.cena = value;
    }

    /**
     * Gets the value of the kodLab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodLab() {
        return kodLab;
    }

    /**
     * Sets the value of the kodLab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodLab(String value) {
        this.kodLab = value;
    }

    /**
     * Gets the value of the srCito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrCito() {
        if (srCito == null) {
            return "C";
        } else {
            return srCito;
        }
    }

    /**
     * Sets the value of the srCito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrCito(String value) {
        this.srCito = value;
    }

    /**
     * Gets the value of the srNahrady property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrNahrady() {
        return srNahrady;
    }

    /**
     * Sets the value of the srNahrady property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrNahrady(String value) {
        this.srNahrady = value;
    }

    /**
     * Gets the value of the srKodLek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrKodLek() {
        return srKodLek;
    }

    /**
     * Sets the value of the srKodLek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrKodLek(String value) {
        this.srKodLek = value;
    }

    /**
     * Gets the value of the srMnozstvi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrMnozstvi() {
        return srMnozstvi;
    }

    /**
     * Sets the value of the srMnozstvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrMnozstvi(String value) {
        this.srMnozstvi = value;
    }

    /**
     * Gets the value of the srCena property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrCena() {
        return srCena;
    }

    /**
     * Sets the value of the srCena property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrCena(String value) {
        this.srCena = value;
    }

}
