//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chpnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chpnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cpn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="ecnicpe" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="cnpc" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str10" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chpnType")
public class ChpnType {

    @XmlAttribute
    protected String cpn;
    @XmlAttribute
    protected String ecnicpe;
    @XmlAttribute
    protected String cnpc;

    /**
     * Gets the value of the cpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpn() {
        return cpn;
    }

    /**
     * Sets the value of the cpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpn(String value) {
        this.cpn = value;
    }

    /**
     * Gets the value of the ecnicpe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcnicpe() {
        return ecnicpe;
    }

    /**
     * Sets the value of the ecnicpe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcnicpe(String value) {
        this.ecnicpe = value;
    }

    /**
     * Gets the value of the cnpc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnpc() {
        return cnpc;
    }

    /**
     * Sets the value of the cnpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnpc(String value) {
        this.cnpc = value;
    }

}
