//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for chyba_pdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chyba_pdType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="kod" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str3" />
 *       &lt;attribute name="lokalizace" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str64" />
 *       &lt;attribute name="osetreni">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="O"/>
 *             &lt;enumeration value="I"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="popis" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chyba_pdType", propOrder = {
    "value"
})
public class ChybaPdType {

    @XmlValue
    protected String value;
    @XmlAttribute(required = true)
    protected String kod;
    @XmlAttribute
    protected String lokalizace;
    @XmlAttribute
    protected String osetreni;
    @XmlAttribute
    protected String popis;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the kod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKod() {
        return kod;
    }

    /**
     * Sets the value of the kod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKod(String value) {
        this.kod = value;
    }

    /**
     * Gets the value of the lokalizace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLokalizace() {
        return lokalizace;
    }

    /**
     * Sets the value of the lokalizace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLokalizace(String value) {
        this.lokalizace = value;
    }

    /**
     * Gets the value of the osetreni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsetreni() {
        return osetreni;
    }

    /**
     * Sets the value of the osetreni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsetreni(String value) {
        this.osetreni = value;
    }

    /**
     * Gets the value of the popis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopis() {
        return popis;
    }

    /**
     * Sets the value of the popis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopis(String value) {
        this.popis = value;
    }

}
