//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.AutorType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatDuType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatXxType;


/**
 * <p>Java class for davkaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="davkaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="autor" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str35" minOccurs="0"/>
 *         &lt;element name="dat_du" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_duType"/>
 *         &lt;element name="reakce" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dat_or" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType"/>
 *                   &lt;element name="vys_or" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
 *                   &lt;element name="autor" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}autorType" minOccurs="0"/>
 *                   &lt;element name="reakceAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="typ" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}davkaTypType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="davkaAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cis_davky" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1d" />
 *       &lt;attribute name="ind_oprav_sd" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}indOprSdType" />
 *       &lt;attribute name="nazev_ol" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str70" />
 *       &lt;attribute name="gene_ol" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str70" />
 *       &lt;attribute name="kod_ol" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str7" />
 *       &lt;attribute name="cis_sarze" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str35" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "davkaType", propOrder = {
    "autor",
    "datDu",
    "reakce",
    "davkaAny"
})
public class DavkaType {

    protected String autor;
    @XmlElement(name = "dat_du", required = true)
    protected DatDuType datDu;
    protected List<DavkaType.Reakce> reakce;
    protected AnyType davkaAny;
    @XmlAttribute(name = "cis_davky", required = true)
    protected BigInteger cisDavky;
    @XmlAttribute(name = "ind_oprav_sd", required = true)
    protected String indOpravSd;
    @XmlAttribute(name = "nazev_ol", required = true)
    protected String nazevOl;
    @XmlAttribute(name = "gene_ol")
    protected String geneOl;
    @XmlAttribute(name = "kod_ol")
    protected String kodOl;
    @XmlAttribute(name = "cis_sarze")
    protected String cisSarze;

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutor(String value) {
        this.autor = value;
    }

    /**
     * Gets the value of the datDu property.
     * 
     * @return
     *     possible object is
     *     {@link DatDuType }
     *     
     */
    public DatDuType getDatDu() {
        return datDu;
    }

    /**
     * Sets the value of the datDu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatDuType }
     *     
     */
    public void setDatDu(DatDuType value) {
        this.datDu = value;
    }

    /**
     * Gets the value of the reakce property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reakce property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReakce().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DavkaType.Reakce }
     * 
     * 
     */
    public List<DavkaType.Reakce> getReakce() {
        if (reakce == null) {
            reakce = new ArrayList<DavkaType.Reakce>();
        }
        return this.reakce;
    }

    /**
     * Gets the value of the davkaAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getDavkaAny() {
        return davkaAny;
    }

    /**
     * Sets the value of the davkaAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setDavkaAny(AnyType value) {
        this.davkaAny = value;
    }

    /**
     * Gets the value of the cisDavky property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCisDavky() {
        return cisDavky;
    }

    /**
     * Sets the value of the cisDavky property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCisDavky(BigInteger value) {
        this.cisDavky = value;
    }

    /**
     * Gets the value of the indOpravSd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndOpravSd() {
        return indOpravSd;
    }

    /**
     * Sets the value of the indOpravSd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndOpravSd(String value) {
        this.indOpravSd = value;
    }

    /**
     * Gets the value of the nazevOl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazevOl() {
        return nazevOl;
    }

    /**
     * Sets the value of the nazevOl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazevOl(String value) {
        this.nazevOl = value;
    }

    /**
     * Gets the value of the geneOl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneOl() {
        return geneOl;
    }

    /**
     * Sets the value of the geneOl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneOl(String value) {
        this.geneOl = value;
    }

    /**
     * Gets the value of the kodOl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodOl() {
        return kodOl;
    }

    /**
     * Sets the value of the kodOl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodOl(String value) {
        this.kodOl = value;
    }

    /**
     * Gets the value of the cisSarze property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCisSarze() {
        return cisSarze;
    }

    /**
     * Sets the value of the cisSarze property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCisSarze(String value) {
        this.cisSarze = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dat_or" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType"/>
     *         &lt;element name="vys_or" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
     *         &lt;element name="autor" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}autorType" minOccurs="0"/>
     *         &lt;element name="reakceAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="typ" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}davkaTypType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datOr",
        "vysOr",
        "autor",
        "reakceAny"
    })
    public static class Reakce {

        @XmlElement(name = "dat_or", required = true)
        protected DatXxType datOr;
        @XmlElement(name = "vys_or")
        protected String vysOr;
        protected AutorType autor;
        protected AnyType reakceAny;
        @XmlAttribute(required = true)
        protected String typ;

        /**
         * Gets the value of the datOr property.
         * 
         * @return
         *     possible object is
         *     {@link DatXxType }
         *     
         */
        public DatXxType getDatOr() {
            return datOr;
        }

        /**
         * Sets the value of the datOr property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatXxType }
         *     
         */
        public void setDatOr(DatXxType value) {
            this.datOr = value;
        }

        /**
         * Gets the value of the vysOr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVysOr() {
            return vysOr;
        }

        /**
         * Sets the value of the vysOr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVysOr(String value) {
            this.vysOr = value;
        }

        /**
         * Gets the value of the autor property.
         * 
         * @return
         *     possible object is
         *     {@link AutorType }
         *     
         */
        public AutorType getAutor() {
            return autor;
        }

        /**
         * Sets the value of the autor property.
         * 
         * @param value
         *     allowed object is
         *     {@link AutorType }
         *     
         */
        public void setAutor(AutorType value) {
            this.autor = value;
        }

        /**
         * Gets the value of the reakceAny property.
         * 
         * @return
         *     possible object is
         *     {@link AnyType }
         *     
         */
        public AnyType getReakceAny() {
            return reakceAny;
        }

        /**
         * Sets the value of the reakceAny property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyType }
         *     
         */
        public void setReakceAny(AnyType value) {
            this.reakceAny = value;
        }

        /**
         * Gets the value of the typ property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTyp() {
            return typ;
        }

        /**
         * Sets the value of the typ property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTyp(String value) {
            this.typ = value;
        }

    }

}
