//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.AutorType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatDuType;


/**
 * <p>Java class for dgzType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dgzType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="diag">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;urn:cz-mzcr:ns:dasta:ds4:ds_type>str5">
 *                 &lt;attribute name="poradi" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1-99" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dat_du" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_duType" minOccurs="0"/>
 *         &lt;element name="spec_dg" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str120" minOccurs="0"/>
 *         &lt;element name="autor" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}autorType" minOccurs="0"/>
 *         &lt;element name="dgzAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typ_dg" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;pattern value="[TP]"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ind_oprav_sd" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}indOprSdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dgzType", propOrder = {
    "diag",
    "datDu",
    "specDg",
    "autor",
    "dgzAny"
})
public class DgzType {

    @XmlElement(required = true)
    protected DgzType.Diag diag;
    @XmlElement(name = "dat_du")
    protected DatDuType datDu;
    @XmlElement(name = "spec_dg")
    protected String specDg;
    protected AutorType autor;
    protected AnyType dgzAny;
    @XmlAttribute(name = "typ_dg", required = true)
    protected String typDg;
    @XmlAttribute(name = "ind_oprav_sd", required = true)
    protected String indOpravSd;

    /**
     * Gets the value of the diag property.
     * 
     * @return
     *     possible object is
     *     {@link DgzType.Diag }
     *     
     */
    public DgzType.Diag getDiag() {
        return diag;
    }

    /**
     * Sets the value of the diag property.
     * 
     * @param value
     *     allowed object is
     *     {@link DgzType.Diag }
     *     
     */
    public void setDiag(DgzType.Diag value) {
        this.diag = value;
    }

    /**
     * Gets the value of the datDu property.
     * 
     * @return
     *     possible object is
     *     {@link DatDuType }
     *     
     */
    public DatDuType getDatDu() {
        return datDu;
    }

    /**
     * Sets the value of the datDu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatDuType }
     *     
     */
    public void setDatDu(DatDuType value) {
        this.datDu = value;
    }

    /**
     * Gets the value of the specDg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecDg() {
        return specDg;
    }

    /**
     * Sets the value of the specDg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecDg(String value) {
        this.specDg = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link AutorType }
     *     
     */
    public AutorType getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutorType }
     *     
     */
    public void setAutor(AutorType value) {
        this.autor = value;
    }

    /**
     * Gets the value of the dgzAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getDgzAny() {
        return dgzAny;
    }

    /**
     * Sets the value of the dgzAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setDgzAny(AnyType value) {
        this.dgzAny = value;
    }

    /**
     * Gets the value of the typDg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypDg() {
        return typDg;
    }

    /**
     * Sets the value of the typDg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypDg(String value) {
        this.typDg = value;
    }

    /**
     * Gets the value of the indOpravSd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndOpravSd() {
        return indOpravSd;
    }

    /**
     * Sets the value of the indOpravSd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndOpravSd(String value) {
        this.indOpravSd = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;urn:cz-mzcr:ns:dasta:ds4:ds_type>str5">
     *       &lt;attribute name="poradi" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1-99" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Diag {

        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected int poradi;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the poradi property.
         * 
         */
        public int getPoradi() {
            return poradi;
        }

        /**
         * Sets the value of the poradi property.
         * 
         */
        public void setPoradi(int value) {
            this.poradi = value;
        }

    }

}
