//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hpnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hpnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chpn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}chpnType"/>
 *         &lt;element name="idl" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}idlType"/>
 *         &lt;element name="ahpn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}ahpnType" minOccurs="0"/>
 *         &lt;element name="izam" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}izamType" minOccurs="0"/>
 *         &lt;element name="vchz" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vchzType" minOccurs="0"/>
 *         &lt;element name="hsp" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}hspType" minOccurs="0"/>
 *         &lt;element name="zpshl" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}zpshlType" minOccurs="0"/>
 *         &lt;element name="astat" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str2e" minOccurs="0"/>
 *         &lt;element name="dath_diag_zm" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType" minOccurs="0"/>
 *         &lt;element name="urssz" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}ursszType" minOccurs="0"/>
 *         &lt;element name="pece_zm" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}pece_zmType" minOccurs="0"/>
 *         &lt;element name="porus_rzm_pozn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str200" minOccurs="0"/>
 *         &lt;element name="dath_od" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType" minOccurs="0"/>
 *         &lt;element name="dath_du" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType" minOccurs="0"/>
 *         &lt;element name="dath_ru" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType" minOccurs="0"/>
 *         &lt;element name="dath_do" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cfrm" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number4d" />
 *       &lt;attribute name="tfrm" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="H"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ind_oprav_sd">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="E"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="diag_poc" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str4" />
 *       &lt;attribute name="uraz_kod">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="P"/>
 *             &lt;enumeration value="J"/>
 *             &lt;enumeration value="O"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="alkoml">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="diag_kon" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str4" />
 *       &lt;attribute name="diag_zm" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str4" />
 *       &lt;attribute name="uk_duvod" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1" />
 *       &lt;attribute name="ind_porus_rzm">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hpnType", propOrder = {
    "chpn",
    "idl",
    "ahpn",
    "izam",
    "vchz",
    "hsp",
    "zpshl",
    "astat",
    "dathDiagZm",
    "urssz",
    "peceZm",
    "porusRzmPozn",
    "dathOd",
    "dathDu",
    "dathRu",
    "dathDo"
})
public class HpnType {

    @XmlElement(required = true)
    protected ChpnType chpn;
    @XmlElement(required = true)
    protected IdlType idl;
    protected AhpnType ahpn;
    protected IzamType izam;
    protected VchzType vchz;
    protected HspType hsp;
    protected ZpshlType zpshl;
    protected String astat;
    @XmlElement(name = "dath_diag_zm")
    protected DathXxType dathDiagZm;
    protected UrsszType urssz;
    @XmlElement(name = "pece_zm")
    protected PeceZmType peceZm;
    @XmlElement(name = "porus_rzm_pozn")
    protected String porusRzmPozn;
    @XmlElement(name = "dath_od")
    protected DathXxType dathOd;
    @XmlElement(name = "dath_du")
    protected DathXxType dathDu;
    @XmlElement(name = "dath_ru")
    protected DathXxType dathRu;
    @XmlElement(name = "dath_do")
    protected DathXxType dathDo;
    @XmlAttribute(required = true)
    protected BigInteger cfrm;
    @XmlAttribute(required = true)
    protected String tfrm;
    @XmlAttribute(name = "ind_oprav_sd")
    protected String indOpravSd;
    @XmlAttribute(name = "diag_poc")
    protected String diagPoc;
    @XmlAttribute(name = "uraz_kod")
    protected String urazKod;
    @XmlAttribute
    protected String alkoml;
    @XmlAttribute(name = "diag_kon")
    protected String diagKon;
    @XmlAttribute(name = "diag_zm")
    protected String diagZm;
    @XmlAttribute(name = "uk_duvod")
    protected String ukDuvod;
    @XmlAttribute(name = "ind_porus_rzm")
    protected String indPorusRzm;

    /**
     * Gets the value of the chpn property.
     * 
     * @return
     *     possible object is
     *     {@link ChpnType }
     *     
     */
    public ChpnType getChpn() {
        return chpn;
    }

    /**
     * Sets the value of the chpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChpnType }
     *     
     */
    public void setChpn(ChpnType value) {
        this.chpn = value;
    }

    /**
     * Gets the value of the idl property.
     * 
     * @return
     *     possible object is
     *     {@link IdlType }
     *     
     */
    public IdlType getIdl() {
        return idl;
    }

    /**
     * Sets the value of the idl property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdlType }
     *     
     */
    public void setIdl(IdlType value) {
        this.idl = value;
    }

    /**
     * Gets the value of the ahpn property.
     * 
     * @return
     *     possible object is
     *     {@link AhpnType }
     *     
     */
    public AhpnType getAhpn() {
        return ahpn;
    }

    /**
     * Sets the value of the ahpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link AhpnType }
     *     
     */
    public void setAhpn(AhpnType value) {
        this.ahpn = value;
    }

    /**
     * Gets the value of the izam property.
     * 
     * @return
     *     possible object is
     *     {@link IzamType }
     *     
     */
    public IzamType getIzam() {
        return izam;
    }

    /**
     * Sets the value of the izam property.
     * 
     * @param value
     *     allowed object is
     *     {@link IzamType }
     *     
     */
    public void setIzam(IzamType value) {
        this.izam = value;
    }

    /**
     * Gets the value of the vchz property.
     * 
     * @return
     *     possible object is
     *     {@link VchzType }
     *     
     */
    public VchzType getVchz() {
        return vchz;
    }

    /**
     * Sets the value of the vchz property.
     * 
     * @param value
     *     allowed object is
     *     {@link VchzType }
     *     
     */
    public void setVchz(VchzType value) {
        this.vchz = value;
    }

    /**
     * Gets the value of the hsp property.
     * 
     * @return
     *     possible object is
     *     {@link HspType }
     *     
     */
    public HspType getHsp() {
        return hsp;
    }

    /**
     * Sets the value of the hsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link HspType }
     *     
     */
    public void setHsp(HspType value) {
        this.hsp = value;
    }

    /**
     * Gets the value of the zpshl property.
     * 
     * @return
     *     possible object is
     *     {@link ZpshlType }
     *     
     */
    public ZpshlType getZpshl() {
        return zpshl;
    }

    /**
     * Sets the value of the zpshl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZpshlType }
     *     
     */
    public void setZpshl(ZpshlType value) {
        this.zpshl = value;
    }

    /**
     * Gets the value of the astat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAstat() {
        return astat;
    }

    /**
     * Sets the value of the astat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAstat(String value) {
        this.astat = value;
    }

    /**
     * Gets the value of the dathDiagZm property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathDiagZm() {
        return dathDiagZm;
    }

    /**
     * Sets the value of the dathDiagZm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathDiagZm(DathXxType value) {
        this.dathDiagZm = value;
    }

    /**
     * Gets the value of the urssz property.
     * 
     * @return
     *     possible object is
     *     {@link UrsszType }
     *     
     */
    public UrsszType getUrssz() {
        return urssz;
    }

    /**
     * Sets the value of the urssz property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrsszType }
     *     
     */
    public void setUrssz(UrsszType value) {
        this.urssz = value;
    }

    /**
     * Gets the value of the peceZm property.
     * 
     * @return
     *     possible object is
     *     {@link PeceZmType }
     *     
     */
    public PeceZmType getPeceZm() {
        return peceZm;
    }

    /**
     * Sets the value of the peceZm property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeceZmType }
     *     
     */
    public void setPeceZm(PeceZmType value) {
        this.peceZm = value;
    }

    /**
     * Gets the value of the porusRzmPozn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPorusRzmPozn() {
        return porusRzmPozn;
    }

    /**
     * Sets the value of the porusRzmPozn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPorusRzmPozn(String value) {
        this.porusRzmPozn = value;
    }

    /**
     * Gets the value of the dathOd property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathOd() {
        return dathOd;
    }

    /**
     * Sets the value of the dathOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathOd(DathXxType value) {
        this.dathOd = value;
    }

    /**
     * Gets the value of the dathDu property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathDu() {
        return dathDu;
    }

    /**
     * Sets the value of the dathDu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathDu(DathXxType value) {
        this.dathDu = value;
    }

    /**
     * Gets the value of the dathRu property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathRu() {
        return dathRu;
    }

    /**
     * Sets the value of the dathRu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathRu(DathXxType value) {
        this.dathRu = value;
    }

    /**
     * Gets the value of the dathDo property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathDo() {
        return dathDo;
    }

    /**
     * Sets the value of the dathDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathDo(DathXxType value) {
        this.dathDo = value;
    }

    /**
     * Gets the value of the cfrm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCfrm() {
        return cfrm;
    }

    /**
     * Sets the value of the cfrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCfrm(BigInteger value) {
        this.cfrm = value;
    }

    /**
     * Gets the value of the tfrm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTfrm() {
        return tfrm;
    }

    /**
     * Sets the value of the tfrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTfrm(String value) {
        this.tfrm = value;
    }

    /**
     * Gets the value of the indOpravSd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndOpravSd() {
        return indOpravSd;
    }

    /**
     * Sets the value of the indOpravSd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndOpravSd(String value) {
        this.indOpravSd = value;
    }

    /**
     * Gets the value of the diagPoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagPoc() {
        return diagPoc;
    }

    /**
     * Sets the value of the diagPoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagPoc(String value) {
        this.diagPoc = value;
    }

    /**
     * Gets the value of the urazKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrazKod() {
        return urazKod;
    }

    /**
     * Sets the value of the urazKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrazKod(String value) {
        this.urazKod = value;
    }

    /**
     * Gets the value of the alkoml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlkoml() {
        return alkoml;
    }

    /**
     * Sets the value of the alkoml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlkoml(String value) {
        this.alkoml = value;
    }

    /**
     * Gets the value of the diagKon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagKon() {
        return diagKon;
    }

    /**
     * Sets the value of the diagKon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagKon(String value) {
        this.diagKon = value;
    }

    /**
     * Gets the value of the diagZm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagZm() {
        return diagZm;
    }

    /**
     * Sets the value of the diagZm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagZm(String value) {
        this.diagZm = value;
    }

    /**
     * Gets the value of the ukDuvod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUkDuvod() {
        return ukDuvod;
    }

    /**
     * Sets the value of the ukDuvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUkDuvod(String value) {
        this.ukDuvod = value;
    }

    /**
     * Gets the value of the indPorusRzm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndPorusRzm() {
        return indPorusRzm;
    }

    /**
     * Sets the value of the indPorusRzm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndPorusRzm(String value) {
        this.indPorusRzm = value;
    }

}
