//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for kolize_vType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kolize_vType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:cz-mzcr:ns:dasta:ds4:ds_type>str1">
 *       &lt;attribute name="stav" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1-7" />
 *       &lt;attribute name="err" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str3e" />
 *       &lt;attribute name="klic_nclp" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str5e" />
 *       &lt;attribute name="klic_nclp_novy" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str5e" />
 *       &lt;attribute name="pozn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str50" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kolize_vType", propOrder = {
    "value"
})
public class KolizeVType {

    @XmlValue
    protected String value;
    @XmlAttribute(required = true)
    protected String stav;
    @XmlAttribute(required = true)
    protected String err;
    @XmlAttribute(name = "klic_nclp")
    protected String klicNclp;
    @XmlAttribute(name = "klic_nclp_novy")
    protected String klicNclpNovy;
    @XmlAttribute
    protected String pozn;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the stav property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStav() {
        return stav;
    }

    /**
     * Sets the value of the stav property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStav(String value) {
        this.stav = value;
    }

    /**
     * Gets the value of the err property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErr() {
        return err;
    }

    /**
     * Sets the value of the err property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErr(String value) {
        this.err = value;
    }

    /**
     * Gets the value of the klicNclp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlicNclp() {
        return klicNclp;
    }

    /**
     * Sets the value of the klicNclp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlicNclp(String value) {
        this.klicNclp = value;
    }

    /**
     * Gets the value of the klicNclpNovy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlicNclpNovy() {
        return klicNclpNovy;
    }

    /**
     * Sets the value of the klicNclpNovy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlicNclpNovy(String value) {
        this.klicNclpNovy = value;
    }

    /**
     * Gets the value of the pozn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPozn() {
        return pozn;
    }

    /**
     * Sets the value of the pozn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPozn(String value) {
        this.pozn = value;
    }

}
