//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LODO;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LOTDV;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LOUP;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatDuType;


/**
 * <p>Java class for ku_o_labType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ku_o_labType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="los" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}losType" minOccurs="0"/>
 *         &lt;element name="dat_du" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_duType"/>
 *         &lt;element name="lip" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}lipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="loi" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}loiType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="lop" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}lopType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="lopk" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}lopkType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="lopz" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}lopzType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="lopr" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}loprType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="kuolabAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id_lo_is" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str15" />
 *       &lt;attribute name="urg" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LOUP" default="R" />
 *       &lt;attribute name="dodani" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LOTDV" default="B" />
 *       &lt;attribute name="duv_objed" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LODO" default="B" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ku_o_labType", propOrder = {
    "los",
    "datDu",
    "lip",
    "loi",
    "lop",
    "lopk",
    "lopz",
    "lopr",
    "kuolabAny"
})
public class KuOLabType {

    protected LosType los;
    @XmlElement(name = "dat_du", required = true)
    protected DatDuType datDu;
    protected List<LipType> lip;
    protected List<LoiType> loi;
    protected List<LopType> lop;
    protected List<LopkType> lopk;
    protected List<LopzType> lopz;
    protected List<LoprType> lopr;
    protected AnyType kuolabAny;
    @XmlAttribute(name = "id_lo_is", required = true)
    protected String idLoIs;
    @XmlAttribute
    protected LOUP urg;
    @XmlAttribute
    protected LOTDV dodani;
    @XmlAttribute(name = "duv_objed")
    protected LODO duvObjed;

    /**
     * Gets the value of the los property.
     * 
     * @return
     *     possible object is
     *     {@link LosType }
     *     
     */
    public LosType getLos() {
        return los;
    }

    /**
     * Sets the value of the los property.
     * 
     * @param value
     *     allowed object is
     *     {@link LosType }
     *     
     */
    public void setLos(LosType value) {
        this.los = value;
    }

    /**
     * Gets the value of the datDu property.
     * 
     * @return
     *     possible object is
     *     {@link DatDuType }
     *     
     */
    public DatDuType getDatDu() {
        return datDu;
    }

    /**
     * Sets the value of the datDu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatDuType }
     *     
     */
    public void setDatDu(DatDuType value) {
        this.datDu = value;
    }

    /**
     * Gets the value of the lip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LipType }
     * 
     * 
     */
    public List<LipType> getLip() {
        if (lip == null) {
            lip = new ArrayList<LipType>();
        }
        return this.lip;
    }

    /**
     * Gets the value of the loi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoiType }
     * 
     * 
     */
    public List<LoiType> getLoi() {
        if (loi == null) {
            loi = new ArrayList<LoiType>();
        }
        return this.loi;
    }

    /**
     * Gets the value of the lop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLop().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LopType }
     * 
     * 
     */
    public List<LopType> getLop() {
        if (lop == null) {
            lop = new ArrayList<LopType>();
        }
        return this.lop;
    }

    /**
     * Gets the value of the lopk property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lopk property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLopk().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LopkType }
     * 
     * 
     */
    public List<LopkType> getLopk() {
        if (lopk == null) {
            lopk = new ArrayList<LopkType>();
        }
        return this.lopk;
    }

    /**
     * Gets the value of the lopz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lopz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLopz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LopzType }
     * 
     * 
     */
    public List<LopzType> getLopz() {
        if (lopz == null) {
            lopz = new ArrayList<LopzType>();
        }
        return this.lopz;
    }

    /**
     * Gets the value of the lopr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lopr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLopr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoprType }
     * 
     * 
     */
    public List<LoprType> getLopr() {
        if (lopr == null) {
            lopr = new ArrayList<LoprType>();
        }
        return this.lopr;
    }

    /**
     * Gets the value of the kuolabAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getKuolabAny() {
        return kuolabAny;
    }

    /**
     * Sets the value of the kuolabAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setKuolabAny(AnyType value) {
        this.kuolabAny = value;
    }

    /**
     * Gets the value of the idLoIs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdLoIs() {
        return idLoIs;
    }

    /**
     * Sets the value of the idLoIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdLoIs(String value) {
        this.idLoIs = value;
    }

    /**
     * Gets the value of the urg property.
     * 
     * @return
     *     possible object is
     *     {@link LOUP }
     *     
     */
    public LOUP getUrg() {
        if (urg == null) {
            return LOUP.R;
        } else {
            return urg;
        }
    }

    /**
     * Sets the value of the urg property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOUP }
     *     
     */
    public void setUrg(LOUP value) {
        this.urg = value;
    }

    /**
     * Gets the value of the dodani property.
     * 
     * @return
     *     possible object is
     *     {@link LOTDV }
     *     
     */
    public LOTDV getDodani() {
        if (dodani == null) {
            return LOTDV.B;
        } else {
            return dodani;
        }
    }

    /**
     * Sets the value of the dodani property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOTDV }
     *     
     */
    public void setDodani(LOTDV value) {
        this.dodani = value;
    }

    /**
     * Gets the value of the duvObjed property.
     * 
     * @return
     *     possible object is
     *     {@link LODO }
     *     
     */
    public LODO getDuvObjed() {
        if (duvObjed == null) {
            return LODO.B;
        } else {
            return duvObjed;
        }
    }

    /**
     * Sets the value of the duvObjed property.
     * 
     * @param value
     *     allowed object is
     *     {@link LODO }
     *     
     */
    public void setDuvObjed(LODO value) {
        this.duvObjed = value;
    }

}
