//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatXxType;


/**
 * <p>Java class for ku_oType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ku_oType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dat_poz" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType"/>
 *         &lt;element name="dat_prov_od" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *         &lt;element name="dat_prov_do" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *         &lt;element name="z_pracoviste" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}pracovisteType"/>
 *         &lt;element name="z_pracovnik" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}pracovnikType" minOccurs="0"/>
 *         &lt;element name="p_pracoviste" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}pracovisteType" minOccurs="0"/>
 *         &lt;element name="p_pracovnik" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}pracovnikType" minOccurs="0"/>
 *         &lt;element name="dg_poz" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dgzType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lek_poz" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}leType" minOccurs="0"/>
 *         &lt;element name="urg_poz" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}uType" minOccurs="0"/>
 *         &lt;element name="leg_vyk" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}legVykType" minOccurs="0"/>
 *         &lt;element name="ku_prilohy" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str64" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="text_zadosti" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}textType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="ku_o_rdg" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}ku_o_rdgType" minOccurs="0"/>
 *           &lt;element name="ku_o_lab" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}ku_o_labType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="kuoAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typku" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str20" />
 *       &lt;attribute name="typkuspeclok" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str40" />
 *       &lt;attribute name="fazespec" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="OR"/>
 *             &lt;enumeration value="OO"/>
 *             &lt;enumeration value="OS"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="idku" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}idkuType" />
 *       &lt;attribute name="idkulok" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}idkuType" />
 *       &lt;attribute name="urgentni" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}logicalA" />
 *       &lt;attribute name="handicap" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str80" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ku_oType", propOrder = {
    "datPoz",
    "datProvOd",
    "datProvDo",
    "zPracoviste",
    "zPracovnik",
    "pPracoviste",
    "pPracovnik",
    "dgPoz",
    "lekPoz",
    "urgPoz",
    "legVyk",
    "kuPrilohy",
    "textZadosti",
    "kuORdg",
    "kuOLab",
    "kuoAny"
})
public class KuOType {

    @XmlElement(name = "dat_poz", required = true)
    protected DatXxType datPoz;
    @XmlElement(name = "dat_prov_od")
    protected DatXxType datProvOd;
    @XmlElement(name = "dat_prov_do")
    protected DatXxType datProvDo;
    @XmlElement(name = "z_pracoviste", required = true)
    protected PracovisteType zPracoviste;
    @XmlElement(name = "z_pracovnik")
    protected PracovnikType zPracovnik;
    @XmlElement(name = "p_pracoviste")
    protected PracovisteType pPracoviste;
    @XmlElement(name = "p_pracovnik")
    protected PracovnikType pPracovnik;
    @XmlElement(name = "dg_poz")
    protected List<DgzType> dgPoz;
    @XmlElement(name = "lek_poz")
    protected LeType lekPoz;
    @XmlElement(name = "urg_poz")
    protected UType urgPoz;
    @XmlElement(name = "leg_vyk")
    protected LegVykType legVyk;
    @XmlElement(name = "ku_prilohy")
    protected List<String> kuPrilohy;
    @XmlElement(name = "text_zadosti")
    protected TextType textZadosti;
    @XmlElement(name = "ku_o_rdg")
    protected KuORdgType kuORdg;
    @XmlElement(name = "ku_o_lab")
    protected KuOLabType kuOLab;
    protected AnyType kuoAny;
    @XmlAttribute(required = true)
    protected String typku;
    @XmlAttribute
    protected String typkuspeclok;
    @XmlAttribute(required = true)
    protected String fazespec;
    @XmlAttribute(required = true)
    protected String idku;
    @XmlAttribute
    protected String idkulok;
    @XmlAttribute
    protected String urgentni;
    @XmlAttribute
    protected String handicap;

    /**
     * Gets the value of the datPoz property.
     * 
     * @return
     *     possible object is
     *     {@link DatXxType }
     *     
     */
    public DatXxType getDatPoz() {
        return datPoz;
    }

    /**
     * Sets the value of the datPoz property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatXxType }
     *     
     */
    public void setDatPoz(DatXxType value) {
        this.datPoz = value;
    }

    /**
     * Gets the value of the datProvOd property.
     * 
     * @return
     *     possible object is
     *     {@link DatXxType }
     *     
     */
    public DatXxType getDatProvOd() {
        return datProvOd;
    }

    /**
     * Sets the value of the datProvOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatXxType }
     *     
     */
    public void setDatProvOd(DatXxType value) {
        this.datProvOd = value;
    }

    /**
     * Gets the value of the datProvDo property.
     * 
     * @return
     *     possible object is
     *     {@link DatXxType }
     *     
     */
    public DatXxType getDatProvDo() {
        return datProvDo;
    }

    /**
     * Sets the value of the datProvDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatXxType }
     *     
     */
    public void setDatProvDo(DatXxType value) {
        this.datProvDo = value;
    }

    /**
     * Gets the value of the zPracoviste property.
     * 
     * @return
     *     possible object is
     *     {@link PracovisteType }
     *     
     */
    public PracovisteType getZPracoviste() {
        return zPracoviste;
    }

    /**
     * Sets the value of the zPracoviste property.
     * 
     * @param value
     *     allowed object is
     *     {@link PracovisteType }
     *     
     */
    public void setZPracoviste(PracovisteType value) {
        this.zPracoviste = value;
    }

    /**
     * Gets the value of the zPracovnik property.
     * 
     * @return
     *     possible object is
     *     {@link PracovnikType }
     *     
     */
    public PracovnikType getZPracovnik() {
        return zPracovnik;
    }

    /**
     * Sets the value of the zPracovnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link PracovnikType }
     *     
     */
    public void setZPracovnik(PracovnikType value) {
        this.zPracovnik = value;
    }

    /**
     * Gets the value of the pPracoviste property.
     * 
     * @return
     *     possible object is
     *     {@link PracovisteType }
     *     
     */
    public PracovisteType getPPracoviste() {
        return pPracoviste;
    }

    /**
     * Sets the value of the pPracoviste property.
     * 
     * @param value
     *     allowed object is
     *     {@link PracovisteType }
     *     
     */
    public void setPPracoviste(PracovisteType value) {
        this.pPracoviste = value;
    }

    /**
     * Gets the value of the pPracovnik property.
     * 
     * @return
     *     possible object is
     *     {@link PracovnikType }
     *     
     */
    public PracovnikType getPPracovnik() {
        return pPracovnik;
    }

    /**
     * Sets the value of the pPracovnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link PracovnikType }
     *     
     */
    public void setPPracovnik(PracovnikType value) {
        this.pPracovnik = value;
    }

    /**
     * Gets the value of the dgPoz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dgPoz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDgPoz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DgzType }
     * 
     * 
     */
    public List<DgzType> getDgPoz() {
        if (dgPoz == null) {
            dgPoz = new ArrayList<DgzType>();
        }
        return this.dgPoz;
    }

    /**
     * Gets the value of the lekPoz property.
     * 
     * @return
     *     possible object is
     *     {@link LeType }
     *     
     */
    public LeType getLekPoz() {
        return lekPoz;
    }

    /**
     * Sets the value of the lekPoz property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeType }
     *     
     */
    public void setLekPoz(LeType value) {
        this.lekPoz = value;
    }

    /**
     * Gets the value of the urgPoz property.
     * 
     * @return
     *     possible object is
     *     {@link UType }
     *     
     */
    public UType getUrgPoz() {
        return urgPoz;
    }

    /**
     * Sets the value of the urgPoz property.
     * 
     * @param value
     *     allowed object is
     *     {@link UType }
     *     
     */
    public void setUrgPoz(UType value) {
        this.urgPoz = value;
    }

    /**
     * Gets the value of the legVyk property.
     * 
     * @return
     *     possible object is
     *     {@link LegVykType }
     *     
     */
    public LegVykType getLegVyk() {
        return legVyk;
    }

    /**
     * Sets the value of the legVyk property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegVykType }
     *     
     */
    public void setLegVyk(LegVykType value) {
        this.legVyk = value;
    }

    /**
     * Gets the value of the kuPrilohy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kuPrilohy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKuPrilohy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKuPrilohy() {
        if (kuPrilohy == null) {
            kuPrilohy = new ArrayList<String>();
        }
        return this.kuPrilohy;
    }

    /**
     * Gets the value of the textZadosti property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getTextZadosti() {
        return textZadosti;
    }

    /**
     * Sets the value of the textZadosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setTextZadosti(TextType value) {
        this.textZadosti = value;
    }

    /**
     * Gets the value of the kuORdg property.
     * 
     * @return
     *     possible object is
     *     {@link KuORdgType }
     *     
     */
    public KuORdgType getKuORdg() {
        return kuORdg;
    }

    /**
     * Sets the value of the kuORdg property.
     * 
     * @param value
     *     allowed object is
     *     {@link KuORdgType }
     *     
     */
    public void setKuORdg(KuORdgType value) {
        this.kuORdg = value;
    }

    /**
     * Gets the value of the kuOLab property.
     * 
     * @return
     *     possible object is
     *     {@link KuOLabType }
     *     
     */
    public KuOLabType getKuOLab() {
        return kuOLab;
    }

    /**
     * Sets the value of the kuOLab property.
     * 
     * @param value
     *     allowed object is
     *     {@link KuOLabType }
     *     
     */
    public void setKuOLab(KuOLabType value) {
        this.kuOLab = value;
    }

    /**
     * Gets the value of the kuoAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getKuoAny() {
        return kuoAny;
    }

    /**
     * Sets the value of the kuoAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setKuoAny(AnyType value) {
        this.kuoAny = value;
    }

    /**
     * Gets the value of the typku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypku() {
        return typku;
    }

    /**
     * Sets the value of the typku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypku(String value) {
        this.typku = value;
    }

    /**
     * Gets the value of the typkuspeclok property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypkuspeclok() {
        return typkuspeclok;
    }

    /**
     * Sets the value of the typkuspeclok property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypkuspeclok(String value) {
        this.typkuspeclok = value;
    }

    /**
     * Gets the value of the fazespec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFazespec() {
        return fazespec;
    }

    /**
     * Sets the value of the fazespec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFazespec(String value) {
        this.fazespec = value;
    }

    /**
     * Gets the value of the idku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdku() {
        return idku;
    }

    /**
     * Sets the value of the idku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdku(String value) {
        this.idku = value;
    }

    /**
     * Gets the value of the idkulok property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdkulok() {
        return idkulok;
    }

    /**
     * Sets the value of the idkulok property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdkulok(String value) {
        this.idkulok = value;
    }

    /**
     * Gets the value of the urgentni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrgentni() {
        return urgentni;
    }

    /**
     * Sets the value of the urgentni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrgentni(String value) {
        this.urgentni = value;
    }

    /**
     * Gets the value of the handicap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandicap() {
        return handicap;
    }

    /**
     * Sets the value of the handicap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandicap(String value) {
        this.handicap = value;
    }

}
