//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LVIVFVN;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LVSVN;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LVTSVN;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LVUIN;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LVUZN;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.AutorType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatDuType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatXxType;
import mzcr.cz.ns.dasta.ds4.ds_type.OdeslalType;


/**
 * <p>Java class for ku_z_labType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ku_z_labType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dat_du" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_duType"/>
 *         &lt;element name="dat_zt" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *         &lt;element name="dat_pl" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *         &lt;element name="dat_vv" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *         &lt;element name="autor" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}autorType" minOccurs="0"/>
 *         &lt;element name="odeslal" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}odeslalType" minOccurs="0"/>
 *         &lt;element name="sci" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}sciType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="nazev_lclp" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str120"/>
 *         &lt;choice>
 *           &lt;element name="vrn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrnType"/>
 *           &lt;element name="vrf" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrfType"/>
 *           &lt;element name="vrs" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrsType"/>
 *           &lt;element name="vrx" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrxType"/>
 *           &lt;element name="vrk" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrkType"/>
 *           &lt;element name="vrb" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrbType"/>
 *           &lt;element name="vrr" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrrType"/>
 *           &lt;element name="vrd" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrdType"/>
 *           &lt;element name="vrp" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrpType"/>
 *           &lt;element name="vro" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vroType"/>
 *           &lt;element name="vrz" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrzType"/>
 *         &lt;/choice>
 *         &lt;element name="kuzlabAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="klic_nclp" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}klic_nclpType" />
 *       &lt;attribute name="klic_nclp_o" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}klic_nclpType" />
 *       &lt;attribute name="typ_cispol" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="L"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="typpol_fh" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="stav_vys" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LVSVN" />
 *       &lt;attribute name="urg_info" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LVUIN" />
 *       &lt;attribute name="urg_zprac" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LVUZN" />
 *       &lt;attribute name="typ_sdel_vys" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LVTSVN" />
 *       &lt;attribute name="ind_vazb_fv" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LVIVFVN" />
 *       &lt;attribute name="ind_test_nf" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number0-2" />
 *       &lt;attribute name="kolize" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="akreditace" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}logicalA" />
 *       &lt;attribute name="duverne" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}logicalA" />
 *       &lt;attribute name="id_lis" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str64" />
 *       &lt;attribute name="id_lo_is" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str16" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ku_z_labType", propOrder = {
    "datDu",
    "datZt",
    "datPl",
    "datVv",
    "autor",
    "odeslal",
    "sci",
    "nazevLclp",
    "vrn",
    "vrf",
    "vrs",
    "vrx",
    "vrk",
    "vrb",
    "vrr",
    "vrd",
    "vrp",
    "vro",
    "vrz",
    "kuzlabAny"
})
public class KuZLabType {

    @XmlElement(name = "dat_du", required = true)
    protected DatDuType datDu;
    @XmlElement(name = "dat_zt")
    protected DatXxType datZt;
    @XmlElement(name = "dat_pl")
    protected DatXxType datPl;
    @XmlElement(name = "dat_vv")
    protected DatXxType datVv;
    protected AutorType autor;
    protected OdeslalType odeslal;
    protected List<SciType> sci;
    @XmlElement(name = "nazev_lclp", required = true)
    protected String nazevLclp;
    protected VrnType vrn;
    protected VrfType vrf;
    protected VrsType vrs;
    protected VrxType vrx;
    protected VrkType vrk;
    protected VrbType vrb;
    protected VrrType vrr;
    protected VrdType vrd;
    protected VrpType vrp;
    protected VroType vro;
    protected VrzType vrz;
    protected AnyType kuzlabAny;
    @XmlAttribute(name = "klic_nclp", required = true)
    protected String klicNclp;
    @XmlAttribute(name = "klic_nclp_o")
    protected String klicNclpO;
    @XmlAttribute(name = "typ_cispol", required = true)
    protected String typCispol;
    @XmlAttribute(name = "typpol_fh", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String typpolFh;
    @XmlAttribute(name = "stav_vys", required = true)
    protected LVSVN stavVys;
    @XmlAttribute(name = "urg_info")
    protected LVUIN urgInfo;
    @XmlAttribute(name = "urg_zprac")
    protected LVUZN urgZprac;
    @XmlAttribute(name = "typ_sdel_vys", required = true)
    protected LVTSVN typSdelVys;
    @XmlAttribute(name = "ind_vazb_fv")
    protected LVIVFVN indVazbFv;
    @XmlAttribute(name = "ind_test_nf")
    protected String indTestNf;
    @XmlAttribute
    protected String kolize;
    @XmlAttribute
    protected String akreditace;
    @XmlAttribute
    protected String duverne;
    @XmlAttribute(name = "id_lis")
    protected String idLis;
    @XmlAttribute(name = "id_lo_is")
    protected String idLoIs;

    /**
     * Gets the value of the datDu property.
     * 
     * @return
     *     possible object is
     *     {@link DatDuType }
     *     
     */
    public DatDuType getDatDu() {
        return datDu;
    }

    /**
     * Sets the value of the datDu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatDuType }
     *     
     */
    public void setDatDu(DatDuType value) {
        this.datDu = value;
    }

    /**
     * Gets the value of the datZt property.
     * 
     * @return
     *     possible object is
     *     {@link DatXxType }
     *     
     */
    public DatXxType getDatZt() {
        return datZt;
    }

    /**
     * Sets the value of the datZt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatXxType }
     *     
     */
    public void setDatZt(DatXxType value) {
        this.datZt = value;
    }

    /**
     * Gets the value of the datPl property.
     * 
     * @return
     *     possible object is
     *     {@link DatXxType }
     *     
     */
    public DatXxType getDatPl() {
        return datPl;
    }

    /**
     * Sets the value of the datPl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatXxType }
     *     
     */
    public void setDatPl(DatXxType value) {
        this.datPl = value;
    }

    /**
     * Gets the value of the datVv property.
     * 
     * @return
     *     possible object is
     *     {@link DatXxType }
     *     
     */
    public DatXxType getDatVv() {
        return datVv;
    }

    /**
     * Sets the value of the datVv property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatXxType }
     *     
     */
    public void setDatVv(DatXxType value) {
        this.datVv = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link AutorType }
     *     
     */
    public AutorType getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutorType }
     *     
     */
    public void setAutor(AutorType value) {
        this.autor = value;
    }

    /**
     * Gets the value of the odeslal property.
     * 
     * @return
     *     possible object is
     *     {@link OdeslalType }
     *     
     */
    public OdeslalType getOdeslal() {
        return odeslal;
    }

    /**
     * Sets the value of the odeslal property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdeslalType }
     *     
     */
    public void setOdeslal(OdeslalType value) {
        this.odeslal = value;
    }

    /**
     * Gets the value of the sci property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sci property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSci().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SciType }
     * 
     * 
     */
    public List<SciType> getSci() {
        if (sci == null) {
            sci = new ArrayList<SciType>();
        }
        return this.sci;
    }

    /**
     * Gets the value of the nazevLclp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazevLclp() {
        return nazevLclp;
    }

    /**
     * Sets the value of the nazevLclp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazevLclp(String value) {
        this.nazevLclp = value;
    }

    /**
     * Gets the value of the vrn property.
     * 
     * @return
     *     possible object is
     *     {@link VrnType }
     *     
     */
    public VrnType getVrn() {
        return vrn;
    }

    /**
     * Sets the value of the vrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrnType }
     *     
     */
    public void setVrn(VrnType value) {
        this.vrn = value;
    }

    /**
     * Gets the value of the vrf property.
     * 
     * @return
     *     possible object is
     *     {@link VrfType }
     *     
     */
    public VrfType getVrf() {
        return vrf;
    }

    /**
     * Sets the value of the vrf property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrfType }
     *     
     */
    public void setVrf(VrfType value) {
        this.vrf = value;
    }

    /**
     * Gets the value of the vrs property.
     * 
     * @return
     *     possible object is
     *     {@link VrsType }
     *     
     */
    public VrsType getVrs() {
        return vrs;
    }

    /**
     * Sets the value of the vrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrsType }
     *     
     */
    public void setVrs(VrsType value) {
        this.vrs = value;
    }

    /**
     * Gets the value of the vrx property.
     * 
     * @return
     *     possible object is
     *     {@link VrxType }
     *     
     */
    public VrxType getVrx() {
        return vrx;
    }

    /**
     * Sets the value of the vrx property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrxType }
     *     
     */
    public void setVrx(VrxType value) {
        this.vrx = value;
    }

    /**
     * Gets the value of the vrk property.
     * 
     * @return
     *     possible object is
     *     {@link VrkType }
     *     
     */
    public VrkType getVrk() {
        return vrk;
    }

    /**
     * Sets the value of the vrk property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrkType }
     *     
     */
    public void setVrk(VrkType value) {
        this.vrk = value;
    }

    /**
     * Gets the value of the vrb property.
     * 
     * @return
     *     possible object is
     *     {@link VrbType }
     *     
     */
    public VrbType getVrb() {
        return vrb;
    }

    /**
     * Sets the value of the vrb property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrbType }
     *     
     */
    public void setVrb(VrbType value) {
        this.vrb = value;
    }

    /**
     * Gets the value of the vrr property.
     * 
     * @return
     *     possible object is
     *     {@link VrrType }
     *     
     */
    public VrrType getVrr() {
        return vrr;
    }

    /**
     * Sets the value of the vrr property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrrType }
     *     
     */
    public void setVrr(VrrType value) {
        this.vrr = value;
    }

    /**
     * Gets the value of the vrd property.
     * 
     * @return
     *     possible object is
     *     {@link VrdType }
     *     
     */
    public VrdType getVrd() {
        return vrd;
    }

    /**
     * Sets the value of the vrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrdType }
     *     
     */
    public void setVrd(VrdType value) {
        this.vrd = value;
    }

    /**
     * Gets the value of the vrp property.
     * 
     * @return
     *     possible object is
     *     {@link VrpType }
     *     
     */
    public VrpType getVrp() {
        return vrp;
    }

    /**
     * Sets the value of the vrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrpType }
     *     
     */
    public void setVrp(VrpType value) {
        this.vrp = value;
    }

    /**
     * Gets the value of the vro property.
     * 
     * @return
     *     possible object is
     *     {@link VroType }
     *     
     */
    public VroType getVro() {
        return vro;
    }

    /**
     * Sets the value of the vro property.
     * 
     * @param value
     *     allowed object is
     *     {@link VroType }
     *     
     */
    public void setVro(VroType value) {
        this.vro = value;
    }

    /**
     * Gets the value of the vrz property.
     * 
     * @return
     *     possible object is
     *     {@link VrzType }
     *     
     */
    public VrzType getVrz() {
        return vrz;
    }

    /**
     * Sets the value of the vrz property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrzType }
     *     
     */
    public void setVrz(VrzType value) {
        this.vrz = value;
    }

    /**
     * Gets the value of the kuzlabAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getKuzlabAny() {
        return kuzlabAny;
    }

    /**
     * Sets the value of the kuzlabAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setKuzlabAny(AnyType value) {
        this.kuzlabAny = value;
    }

    /**
     * Gets the value of the klicNclp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlicNclp() {
        return klicNclp;
    }

    /**
     * Sets the value of the klicNclp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlicNclp(String value) {
        this.klicNclp = value;
    }

    /**
     * Gets the value of the klicNclpO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlicNclpO() {
        return klicNclpO;
    }

    /**
     * Sets the value of the klicNclpO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlicNclpO(String value) {
        this.klicNclpO = value;
    }

    /**
     * Gets the value of the typCispol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypCispol() {
        return typCispol;
    }

    /**
     * Sets the value of the typCispol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypCispol(String value) {
        this.typCispol = value;
    }

    /**
     * Gets the value of the typpolFh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTyppolFh() {
        return typpolFh;
    }

    /**
     * Sets the value of the typpolFh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTyppolFh(String value) {
        this.typpolFh = value;
    }

    /**
     * Gets the value of the stavVys property.
     * 
     * @return
     *     possible object is
     *     {@link LVSVN }
     *     
     */
    public LVSVN getStavVys() {
        return stavVys;
    }

    /**
     * Sets the value of the stavVys property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVSVN }
     *     
     */
    public void setStavVys(LVSVN value) {
        this.stavVys = value;
    }

    /**
     * Gets the value of the urgInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LVUIN }
     *     
     */
    public LVUIN getUrgInfo() {
        return urgInfo;
    }

    /**
     * Sets the value of the urgInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVUIN }
     *     
     */
    public void setUrgInfo(LVUIN value) {
        this.urgInfo = value;
    }

    /**
     * Gets the value of the urgZprac property.
     * 
     * @return
     *     possible object is
     *     {@link LVUZN }
     *     
     */
    public LVUZN getUrgZprac() {
        return urgZprac;
    }

    /**
     * Sets the value of the urgZprac property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVUZN }
     *     
     */
    public void setUrgZprac(LVUZN value) {
        this.urgZprac = value;
    }

    /**
     * Gets the value of the typSdelVys property.
     * 
     * @return
     *     possible object is
     *     {@link LVTSVN }
     *     
     */
    public LVTSVN getTypSdelVys() {
        return typSdelVys;
    }

    /**
     * Sets the value of the typSdelVys property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVTSVN }
     *     
     */
    public void setTypSdelVys(LVTSVN value) {
        this.typSdelVys = value;
    }

    /**
     * Gets the value of the indVazbFv property.
     * 
     * @return
     *     possible object is
     *     {@link LVIVFVN }
     *     
     */
    public LVIVFVN getIndVazbFv() {
        return indVazbFv;
    }

    /**
     * Sets the value of the indVazbFv property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVIVFVN }
     *     
     */
    public void setIndVazbFv(LVIVFVN value) {
        this.indVazbFv = value;
    }

    /**
     * Gets the value of the indTestNf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndTestNf() {
        return indTestNf;
    }

    /**
     * Sets the value of the indTestNf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndTestNf(String value) {
        this.indTestNf = value;
    }

    /**
     * Gets the value of the kolize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKolize() {
        return kolize;
    }

    /**
     * Sets the value of the kolize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKolize(String value) {
        this.kolize = value;
    }

    /**
     * Gets the value of the akreditace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAkreditace() {
        return akreditace;
    }

    /**
     * Sets the value of the akreditace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAkreditace(String value) {
        this.akreditace = value;
    }

    /**
     * Gets the value of the duverne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuverne() {
        return duverne;
    }

    /**
     * Sets the value of the duverne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuverne(String value) {
        this.duverne = value;
    }

    /**
     * Gets the value of the idLis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdLis() {
        return idLis;
    }

    /**
     * Sets the value of the idLis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdLis(String value) {
        this.idLis = value;
    }

    /**
     * Gets the value of the idLoIs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdLoIs() {
        return idLoIs;
    }

    /**
     * Sets the value of the idLoIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdLoIs(String value) {
        this.idLoIs = value;
    }

}
