//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.ProjekceType;


/**
 * <p>Java class for ku_z_rdg_eType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ku_z_rdg_eType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kuzrdgeAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="projekce" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}projekceType" />
 *       &lt;attribute name="napeti" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}realNumber8" />
 *       &lt;attribute name="proud" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}realNumber8" />
 *       &lt;attribute name="el_mnozstvi" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}realNumber8" />
 *       &lt;attribute name="doba" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}realNumber8" />
 *       &lt;attribute name="komprese" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}realNumber8" />
 *       &lt;attribute name="davka_ozareni" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}realNumber8" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ku_z_rdg_eType", propOrder = {
    "kuzrdgeAny"
})
public class KuZRdgEType {

    protected AnyType kuzrdgeAny;
    @XmlAttribute
    protected ProjekceType projekce;
    @XmlAttribute
    protected Float napeti;
    @XmlAttribute
    protected Float proud;
    @XmlAttribute(name = "el_mnozstvi")
    protected Float elMnozstvi;
    @XmlAttribute
    protected Float doba;
    @XmlAttribute
    protected Float komprese;
    @XmlAttribute(name = "davka_ozareni")
    protected Float davkaOzareni;

    /**
     * Gets the value of the kuzrdgeAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getKuzrdgeAny() {
        return kuzrdgeAny;
    }

    /**
     * Sets the value of the kuzrdgeAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setKuzrdgeAny(AnyType value) {
        this.kuzrdgeAny = value;
    }

    /**
     * Gets the value of the projekce property.
     * 
     * @return
     *     possible object is
     *     {@link ProjekceType }
     *     
     */
    public ProjekceType getProjekce() {
        return projekce;
    }

    /**
     * Sets the value of the projekce property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjekceType }
     *     
     */
    public void setProjekce(ProjekceType value) {
        this.projekce = value;
    }

    /**
     * Gets the value of the napeti property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNapeti() {
        return napeti;
    }

    /**
     * Sets the value of the napeti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNapeti(Float value) {
        this.napeti = value;
    }

    /**
     * Gets the value of the proud property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getProud() {
        return proud;
    }

    /**
     * Sets the value of the proud property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setProud(Float value) {
        this.proud = value;
    }

    /**
     * Gets the value of the elMnozstvi property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getElMnozstvi() {
        return elMnozstvi;
    }

    /**
     * Sets the value of the elMnozstvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setElMnozstvi(Float value) {
        this.elMnozstvi = value;
    }

    /**
     * Gets the value of the doba property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDoba() {
        return doba;
    }

    /**
     * Sets the value of the doba property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDoba(Float value) {
        this.doba = value;
    }

    /**
     * Gets the value of the komprese property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getKomprese() {
        return komprese;
    }

    /**
     * Sets the value of the komprese property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setKomprese(Float value) {
        this.komprese = value;
    }

    /**
     * Gets the value of the davkaOzareni property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDavkaOzareni() {
        return davkaOzareni;
    }

    /**
     * Sets the value of the davkaOzareni property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDavkaOzareni(Float value) {
        this.davkaOzareni = value;
    }

}
