//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for legVykType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="legVykType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nahrady" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="legVykAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uraz" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}logicalA" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "legVykType", propOrder = {
    "nahrady",
    "legVykAny"
})
public class LegVykType {

    protected List<String> nahrady;
    protected AnyType legVykAny;
    @XmlAttribute
    protected String uraz;

    /**
     * Gets the value of the nahrady property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nahrady property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNahrady().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNahrady() {
        if (nahrady == null) {
            nahrady = new ArrayList<String>();
        }
        return this.nahrady;
    }

    /**
     * Gets the value of the legVykAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getLegVykAny() {
        return legVykAny;
    }

    /**
     * Sets the value of the legVykAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setLegVykAny(AnyType value) {
        this.legVykAny = value;
    }

    /**
     * Gets the value of the uraz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUraz() {
        return uraz;
    }

    /**
     * Sets the value of the uraz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUraz(String value) {
        this.uraz = value;
    }

}
