//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.AutorType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatXxType;


/**
 * <p>Java class for leType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lez" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dat_od" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *                   &lt;element name="dat_do" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *                   &lt;element name="rozpis_v" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str50" minOccurs="0"/>
 *                   &lt;element name="pozn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str80" minOccurs="0"/>
 *                   &lt;element name="autor" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}autorType" minOccurs="0"/>
 *                   &lt;element name="lezAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="typ_med" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *                       &lt;pattern value="[TP]"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="ind_oprav_sd" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}indOprSdType" />
 *                 &lt;attribute name="nazev_lek" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str70" />
 *                 &lt;attribute name="gene_lek" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str70" />
 *                 &lt;attribute name="kod_lek" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str7" />
 *                 &lt;attribute name="kod_atb" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str3" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="leAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dat_ab" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leType", propOrder = {
    "lez",
    "leAny"
})
public class LeType {

    @XmlElement(required = true)
    protected List<LeType.Lez> lez;
    protected AnyType leAny;
    @XmlAttribute(name = "dat_ab")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datAb;

    /**
     * Gets the value of the lez property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lez property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLez().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LeType.Lez }
     * 
     * 
     */
    public List<LeType.Lez> getLez() {
        if (lez == null) {
            lez = new ArrayList<LeType.Lez>();
        }
        return this.lez;
    }

    /**
     * Gets the value of the leAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getLeAny() {
        return leAny;
    }

    /**
     * Sets the value of the leAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setLeAny(AnyType value) {
        this.leAny = value;
    }

    /**
     * Gets the value of the datAb property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatAb() {
        return datAb;
    }

    /**
     * Sets the value of the datAb property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatAb(XMLGregorianCalendar value) {
        this.datAb = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dat_od" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
     *         &lt;element name="dat_do" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
     *         &lt;element name="rozpis_v" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str50" minOccurs="0"/>
     *         &lt;element name="pozn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str80" minOccurs="0"/>
     *         &lt;element name="autor" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}autorType" minOccurs="0"/>
     *         &lt;element name="lezAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="typ_med" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
     *             &lt;pattern value="[TP]"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="ind_oprav_sd" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}indOprSdType" />
     *       &lt;attribute name="nazev_lek" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str70" />
     *       &lt;attribute name="gene_lek" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str70" />
     *       &lt;attribute name="kod_lek" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str7" />
     *       &lt;attribute name="kod_atb" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str3" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datOd",
        "datDo",
        "rozpisV",
        "pozn",
        "autor",
        "lezAny"
    })
    public static class Lez {

        @XmlElement(name = "dat_od")
        protected DatXxType datOd;
        @XmlElement(name = "dat_do")
        protected DatXxType datDo;
        @XmlElement(name = "rozpis_v")
        protected String rozpisV;
        protected String pozn;
        protected AutorType autor;
        protected AnyType lezAny;
        @XmlAttribute(name = "typ_med", required = true)
        protected String typMed;
        @XmlAttribute(name = "ind_oprav_sd", required = true)
        protected String indOpravSd;
        @XmlAttribute(name = "nazev_lek", required = true)
        protected String nazevLek;
        @XmlAttribute(name = "gene_lek")
        protected String geneLek;
        @XmlAttribute(name = "kod_lek")
        protected String kodLek;
        @XmlAttribute(name = "kod_atb")
        protected String kodAtb;

        /**
         * Gets the value of the datOd property.
         * 
         * @return
         *     possible object is
         *     {@link DatXxType }
         *     
         */
        public DatXxType getDatOd() {
            return datOd;
        }

        /**
         * Sets the value of the datOd property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatXxType }
         *     
         */
        public void setDatOd(DatXxType value) {
            this.datOd = value;
        }

        /**
         * Gets the value of the datDo property.
         * 
         * @return
         *     possible object is
         *     {@link DatXxType }
         *     
         */
        public DatXxType getDatDo() {
            return datDo;
        }

        /**
         * Sets the value of the datDo property.
         * 
         * @param value
         *     allowed object is
         *     {@link DatXxType }
         *     
         */
        public void setDatDo(DatXxType value) {
            this.datDo = value;
        }

        /**
         * Gets the value of the rozpisV property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRozpisV() {
            return rozpisV;
        }

        /**
         * Sets the value of the rozpisV property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRozpisV(String value) {
            this.rozpisV = value;
        }

        /**
         * Gets the value of the pozn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPozn() {
            return pozn;
        }

        /**
         * Sets the value of the pozn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPozn(String value) {
            this.pozn = value;
        }

        /**
         * Gets the value of the autor property.
         * 
         * @return
         *     possible object is
         *     {@link AutorType }
         *     
         */
        public AutorType getAutor() {
            return autor;
        }

        /**
         * Sets the value of the autor property.
         * 
         * @param value
         *     allowed object is
         *     {@link AutorType }
         *     
         */
        public void setAutor(AutorType value) {
            this.autor = value;
        }

        /**
         * Gets the value of the lezAny property.
         * 
         * @return
         *     possible object is
         *     {@link AnyType }
         *     
         */
        public AnyType getLezAny() {
            return lezAny;
        }

        /**
         * Sets the value of the lezAny property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyType }
         *     
         */
        public void setLezAny(AnyType value) {
            this.lezAny = value;
        }

        /**
         * Gets the value of the typMed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypMed() {
            return typMed;
        }

        /**
         * Sets the value of the typMed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypMed(String value) {
            this.typMed = value;
        }

        /**
         * Gets the value of the indOpravSd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndOpravSd() {
            return indOpravSd;
        }

        /**
         * Sets the value of the indOpravSd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndOpravSd(String value) {
            this.indOpravSd = value;
        }

        /**
         * Gets the value of the nazevLek property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazevLek() {
            return nazevLek;
        }

        /**
         * Sets the value of the nazevLek property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazevLek(String value) {
            this.nazevLek = value;
        }

        /**
         * Gets the value of the geneLek property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGeneLek() {
            return geneLek;
        }

        /**
         * Sets the value of the geneLek property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGeneLek(String value) {
            this.geneLek = value;
        }

        /**
         * Gets the value of the kodLek property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKodLek() {
            return kodLek;
        }

        /**
         * Sets the value of the kodLek property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKodLek(String value) {
            this.kodLek = value;
        }

        /**
         * Gets the value of the kodAtb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKodAtb() {
            return kodAtb;
        }

        /**
         * Sets the value of the kodAtb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKodAtb(String value) {
            this.kodAtb = value;
        }

    }

}
