//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LVPHKN;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for lodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lodAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="klic_nclp" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str5e" />
 *       &lt;attribute name="priznak_kvant" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LVPHKN" />
 *       &lt;attribute name="hodnota" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lodType", propOrder = {
    "lodAny"
})
public class LodType {

    protected AnyType lodAny;
    @XmlAttribute(name = "klic_nclp", required = true)
    protected String klicNclp;
    @XmlAttribute(name = "priznak_kvant")
    protected LVPHKN priznakKvant;
    @XmlAttribute(required = true)
    protected String hodnota;

    /**
     * Gets the value of the lodAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getLodAny() {
        return lodAny;
    }

    /**
     * Sets the value of the lodAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setLodAny(AnyType value) {
        this.lodAny = value;
    }

    /**
     * Gets the value of the klicNclp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlicNclp() {
        return klicNclp;
    }

    /**
     * Sets the value of the klicNclp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlicNclp(String value) {
        this.klicNclp = value;
    }

    /**
     * Gets the value of the priznakKvant property.
     * 
     * @return
     *     possible object is
     *     {@link LVPHKN }
     *     
     */
    public LVPHKN getPriznakKvant() {
        return priznakKvant;
    }

    /**
     * Sets the value of the priznakKvant property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVPHKN }
     *     
     */
    public void setPriznakKvant(LVPHKN value) {
        this.priznakKvant = value;
    }

    /**
     * Gets the value of the hodnota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHodnota() {
        return hodnota;
    }

    /**
     * Sets the value of the hodnota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHodnota(String value) {
        this.hodnota = value;
    }

}
