//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for nazvyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nazvyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nazvyAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typ_cispol">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="L"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nadpis_nal" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *       &lt;attribute name="system" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str32" />
 *       &lt;attribute name="material" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str32" />
 *       &lt;attribute name="komponenta" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *       &lt;attribute name="druh_veliciny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str32" />
 *       &lt;attribute name="jednotka" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str20" />
 *       &lt;attribute name="procedura" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str32" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nazvyType", propOrder = {
    "nazvyAny"
})
public class NazvyType {

    protected AnyType nazvyAny;
    @XmlAttribute(name = "typ_cispol")
    protected String typCispol;
    @XmlAttribute(name = "nadpis_nal")
    protected String nadpisNal;
    @XmlAttribute
    protected String system;
    @XmlAttribute
    protected String material;
    @XmlAttribute
    protected String komponenta;
    @XmlAttribute(name = "druh_veliciny")
    protected String druhVeliciny;
    @XmlAttribute
    protected String jednotka;
    @XmlAttribute
    protected String procedura;

    /**
     * Gets the value of the nazvyAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getNazvyAny() {
        return nazvyAny;
    }

    /**
     * Sets the value of the nazvyAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setNazvyAny(AnyType value) {
        this.nazvyAny = value;
    }

    /**
     * Gets the value of the typCispol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypCispol() {
        return typCispol;
    }

    /**
     * Sets the value of the typCispol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypCispol(String value) {
        this.typCispol = value;
    }

    /**
     * Gets the value of the nadpisNal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNadpisNal() {
        return nadpisNal;
    }

    /**
     * Sets the value of the nadpisNal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNadpisNal(String value) {
        this.nadpisNal = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystem(String value) {
        this.system = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterial(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the komponenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomponenta() {
        return komponenta;
    }

    /**
     * Sets the value of the komponenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomponenta(String value) {
        this.komponenta = value;
    }

    /**
     * Gets the value of the druhVeliciny property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDruhVeliciny() {
        return druhVeliciny;
    }

    /**
     * Sets the value of the druhVeliciny property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDruhVeliciny(String value) {
        this.druhVeliciny = value;
    }

    /**
     * Gets the value of the jednotka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJednotka() {
        return jednotka;
    }

    /**
     * Sets the value of the jednotka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJednotka(String value) {
        this.jednotka = value;
    }

    /**
     * Gets the value of the procedura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedura() {
        return procedura;
    }

    /**
     * Sets the value of the procedura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedura(String value) {
        this.procedura = value;
    }

}
