//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for nejistotaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nejistotaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nejist_var1">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nejistvar1Any" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="t_nejist" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1-2" />
 *                 &lt;attribute name="h_nejist" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nejist_var2">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nejistvar2Any" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="t_nejist_n" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1-2" />
 *                 &lt;attribute name="h_nejist_n" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
 *                 &lt;attribute name="k_anal_n" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
 *                 &lt;attribute name="t_nejist_v" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1-2" />
 *                 &lt;attribute name="h_nejist_v" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
 *                 &lt;attribute name="k_anal_v" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nejistotaAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nejistotaType", propOrder = {
    "nejistVar1",
    "nejistVar2",
    "nejistotaAny"
})
public class NejistotaType {

    @XmlElement(name = "nejist_var1", required = true)
    protected NejistotaType.NejistVar1 nejistVar1;
    @XmlElement(name = "nejist_var2", required = true)
    protected NejistotaType.NejistVar2 nejistVar2;
    protected AnyType nejistotaAny;

    /**
     * Gets the value of the nejistVar1 property.
     * 
     * @return
     *     possible object is
     *     {@link NejistotaType.NejistVar1 }
     *     
     */
    public NejistotaType.NejistVar1 getNejistVar1() {
        return nejistVar1;
    }

    /**
     * Sets the value of the nejistVar1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NejistotaType.NejistVar1 }
     *     
     */
    public void setNejistVar1(NejistotaType.NejistVar1 value) {
        this.nejistVar1 = value;
    }

    /**
     * Gets the value of the nejistVar2 property.
     * 
     * @return
     *     possible object is
     *     {@link NejistotaType.NejistVar2 }
     *     
     */
    public NejistotaType.NejistVar2 getNejistVar2() {
        return nejistVar2;
    }

    /**
     * Sets the value of the nejistVar2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NejistotaType.NejistVar2 }
     *     
     */
    public void setNejistVar2(NejistotaType.NejistVar2 value) {
        this.nejistVar2 = value;
    }

    /**
     * Gets the value of the nejistotaAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getNejistotaAny() {
        return nejistotaAny;
    }

    /**
     * Sets the value of the nejistotaAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setNejistotaAny(AnyType value) {
        this.nejistotaAny = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nejistvar1Any" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="t_nejist" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1-2" />
     *       &lt;attribute name="h_nejist" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nejistvar1Any"
    })
    public static class NejistVar1 {

        protected AnyType nejistvar1Any;
        @XmlAttribute(name = "t_nejist")
        protected String tNejist;
        @XmlAttribute(name = "h_nejist", required = true)
        protected String hNejist;

        /**
         * Gets the value of the nejistvar1Any property.
         * 
         * @return
         *     possible object is
         *     {@link AnyType }
         *     
         */
        public AnyType getNejistvar1Any() {
            return nejistvar1Any;
        }

        /**
         * Sets the value of the nejistvar1Any property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyType }
         *     
         */
        public void setNejistvar1Any(AnyType value) {
            this.nejistvar1Any = value;
        }

        /**
         * Gets the value of the tNejist property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTNejist() {
            return tNejist;
        }

        /**
         * Sets the value of the tNejist property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTNejist(String value) {
            this.tNejist = value;
        }

        /**
         * Gets the value of the hNejist property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHNejist() {
            return hNejist;
        }

        /**
         * Sets the value of the hNejist property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHNejist(String value) {
            this.hNejist = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nejistvar2Any" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="t_nejist_n" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1-2" />
     *       &lt;attribute name="h_nejist_n" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
     *       &lt;attribute name="k_anal_n" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
     *       &lt;attribute name="t_nejist_v" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number1-2" />
     *       &lt;attribute name="h_nejist_v" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
     *       &lt;attribute name="k_anal_v" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nejistvar2Any"
    })
    public static class NejistVar2 {

        protected AnyType nejistvar2Any;
        @XmlAttribute(name = "t_nejist_n")
        protected String tNejistN;
        @XmlAttribute(name = "h_nejist_n", required = true)
        protected String hNejistN;
        @XmlAttribute(name = "k_anal_n", required = true)
        protected String kAnalN;
        @XmlAttribute(name = "t_nejist_v")
        protected String tNejistV;
        @XmlAttribute(name = "h_nejist_v", required = true)
        protected String hNejistV;
        @XmlAttribute(name = "k_anal_v", required = true)
        protected String kAnalV;

        /**
         * Gets the value of the nejistvar2Any property.
         * 
         * @return
         *     possible object is
         *     {@link AnyType }
         *     
         */
        public AnyType getNejistvar2Any() {
            return nejistvar2Any;
        }

        /**
         * Sets the value of the nejistvar2Any property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyType }
         *     
         */
        public void setNejistvar2Any(AnyType value) {
            this.nejistvar2Any = value;
        }

        /**
         * Gets the value of the tNejistN property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTNejistN() {
            return tNejistN;
        }

        /**
         * Sets the value of the tNejistN property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTNejistN(String value) {
            this.tNejistN = value;
        }

        /**
         * Gets the value of the hNejistN property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHNejistN() {
            return hNejistN;
        }

        /**
         * Sets the value of the hNejistN property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHNejistN(String value) {
            this.hNejistN = value;
        }

        /**
         * Gets the value of the kAnalN property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKAnalN() {
            return kAnalN;
        }

        /**
         * Sets the value of the kAnalN property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKAnalN(String value) {
            this.kAnalN = value;
        }

        /**
         * Gets the value of the tNejistV property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTNejistV() {
            return tNejistV;
        }

        /**
         * Sets the value of the tNejistV property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTNejistV(String value) {
            this.tNejistV = value;
        }

        /**
         * Gets the value of the hNejistV property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHNejistV() {
            return hNejistV;
        }

        /**
         * Sets the value of the hNejistV property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHNejistV(String value) {
            this.hNejistV = value;
        }

        /**
         * Gets the value of the kAnalV property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKAnalV() {
            return kAnalV;
        }

        /**
         * Sets the value of the kAnalV property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKAnalV(String value) {
            this.kAnalV = value;
        }

    }

}
