//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mzcr.cz.ns.dasta.ds4.ds_ip package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
    
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mzcr.cz.ns.dasta.ds4.ds_ip
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LopzType }
     * 
     */
    public LopzType createLopzType() {
        return new LopzType();
    }

    /**
     * Create an instance of {@link DgzType.Diag }
     * 
     */
    public DgzType.Diag createDgzTypeDiag() {
        return new DgzType.Diag();
    }

    /**
     * Create an instance of {@link VrpType }
     * 
     */
    public VrpType createVrpType() {
        return new VrpType();
    }

    /**
     * Create an instance of {@link VrfType }
     * 
     */
    public VrfType createVrfType() {
        return new VrfType();
    }

    /**
     * Create an instance of {@link NazvyType }
     * 
     */
    public NazvyType createNazvyType() {
        return new NazvyType();
    }

    /**
     * Create an instance of {@link LipType }
     * 
     */
    public LipType createLipType() {
        return new LipType();
    }

    /**
     * Create an instance of {@link VykonType }
     * 
     */
    public VykonType createVykonType() {
        return new VykonType();
    }

    /**
     * Create an instance of {@link UksType }
     * 
     */
    public UksType createUksType() {
        return new UksType();
    }

    /**
     * Create an instance of {@link IpiType }
     * 
     */
    public IpiType createIpiType() {
        return new IpiType();
    }

    /**
     * Create an instance of {@link Ip.Ku }
     * 
     */
    public Ip.Ku createIpKu() {
        return new Ip.Ku();
    }

    /**
     * Create an instance of {@link OcType }
     * 
     */
    public OcType createOcType() {
        return new OcType();
    }

    /**
     * Create an instance of {@link KuZRdgOType }
     * 
     */
    public KuZRdgOType createKuZRdgOType() {
        return new KuZRdgOType();
    }

    /**
     * Create an instance of {@link VrnType }
     * 
     */
    public VrnType createVrnType() {
        return new VrnType();
    }

    /**
     * Create an instance of {@link LopokType }
     * 
     */
    public LopokType createLopokType() {
        return new LopokType();
    }

    /**
     * Create an instance of {@link ZadatelType }
     * 
     */
    public ZadatelType createZadatelType() {
        return new ZadatelType();
    }

    /**
     * Create an instance of {@link DathXxType }
     * 
     */
    public DathXxType createDathXxType() {
        return new DathXxType();
    }

    /**
     * Create an instance of {@link LeType }
     * 
     */
    public LeType createLeType() {
        return new LeType();
    }

    /**
     * Create an instance of {@link AnType }
     * 
     */
    public AnType createAnType() {
        return new AnType();
    }

    /**
     * Create an instance of {@link ZadatelSkType }
     * 
     */
    public ZadatelSkType createZadatelSkType() {
        return new ZadatelSkType();
    }

    /**
     * Create an instance of {@link PdhpnType }
     * 
     */
    public PdhpnType createPdhpnType() {
        return new PdhpnType();
    }

    /**
     * Create an instance of {@link LosType }
     * 
     */
    public LosType createLosType() {
        return new LosType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link VrsHType }
     * 
     */
    public VrsHType createVrsHType() {
        return new VrsHType();
    }

    /**
     * Create an instance of {@link LekType.LekV }
     * 
     */
    public LekType.LekV createLekTypeLekV() {
        return new LekType.LekV();
    }

    /**
     * Create an instance of {@link AhpnType }
     * 
     */
    public AhpnType createAhpnType() {
        return new AhpnType();
    }

    /**
     * Create an instance of {@link KuZRdgType }
     * 
     */
    public KuZRdgType createKuZRdgType() {
        return new KuZRdgType();
    }

    /**
     * Create an instance of {@link PeceZmType }
     * 
     */
    public PeceZmType createPeceZmType() {
        return new PeceZmType();
    }

    /**
     * Create an instance of {@link VrdType }
     * 
     */
    public VrdType createVrdType() {
        return new VrdType();
    }

    /**
     * Create an instance of {@link VrkpaType.Vrac }
     * 
     */
    public VrkpaType.Vrac createVrkpaTypeVrac() {
        return new VrkpaType.Vrac();
    }

    /**
     * Create an instance of {@link NejistotaType.NejistVar2 }
     * 
     */
    public NejistotaType.NejistVar2 createNejistotaTypeNejistVar2() {
        return new NejistotaType.NejistVar2();
    }

    /**
     * Create an instance of {@link IzamType }
     * 
     */
    public IzamType createIzamType() {
        return new IzamType();
    }

    /**
     * Create an instance of {@link PrepocetType }
     * 
     */
    public PrepocetType createPrepocetType() {
        return new PrepocetType();
    }

    /**
     * Create an instance of {@link PnType.Pnz }
     * 
     */
    public PnType.Pnz createPnTypePnz() {
        return new PnType.Pnz();
    }

    /**
     * Create an instance of {@link KuZRdgEType }
     * 
     */
    public KuZRdgEType createKuZRdgEType() {
        return new KuZRdgEType();
    }

    /**
     * Create an instance of {@link VrkpaType.Vrav }
     * 
     */
    public VrkpaType.Vrav createVrkpaTypeVrav() {
        return new VrkpaType.Vrav();
    }

    /**
     * Create an instance of {@link PnType }
     * 
     */
    public PnType createPnType() {
        return new PnType();
    }

    /**
     * Create an instance of {@link PType }
     * 
     */
    public PType createPType() {
        return new PType();
    }

    /**
     * Create an instance of {@link LopType }
     * 
     */
    public LopType createLopType() {
        return new LopType();
    }

    /**
     * Create an instance of {@link OczType }
     * 
     */
    public OczType createOczType() {
        return new OczType();
    }

    /**
     * Create an instance of {@link DgzType }
     * 
     */
    public DgzType createDgzType() {
        return new DgzType();
    }

    /**
     * Create an instance of {@link DgType }
     * 
     */
    public DgType createDgType() {
        return new DgType();
    }

    /**
     * Create an instance of {@link HType }
     * 
     */
    public HType createHType() {
        return new HType();
    }

    /**
     * Create an instance of {@link NejistotaType.NejistVar1 }
     * 
     */
    public NejistotaType.NejistVar1 createNejistotaTypeNejistVar1() {
        return new NejistotaType.NejistVar1();
    }

    /**
     * Create an instance of {@link AuzkuType }
     * 
     */
    public AuzkuType createAuzkuType() {
        return new AuzkuType();
    }

    /**
     * Create an instance of {@link SciType }
     * 
     */
    public SciType createSciType() {
        return new SciType();
    }

    /**
     * Create an instance of {@link NType }
     * 
     */
    public NType createNType() {
        return new NType();
    }

    /**
     * Create an instance of {@link PracovisteType }
     * 
     */
    public PracovisteType createPracovisteType() {
        return new PracovisteType();
    }

    /**
     * Create an instance of {@link LopkType }
     * 
     */
    public LopkType createLopkType() {
        return new LopkType();
    }

    /**
     * Create an instance of {@link KuOLabType }
     * 
     */
    public KuOLabType createKuOLabType() {
        return new KuOLabType();
    }

    /**
     * Create an instance of {@link HpnType }
     * 
     */
    public HpnType createHpnType() {
        return new HpnType();
    }

    /**
     * Create an instance of {@link KuORdgType }
     * 
     */
    public KuORdgType createKuORdgType() {
        return new KuORdgType();
    }

    /**
     * Create an instance of {@link VrkpaType }
     * 
     */
    public VrkpaType createVrkpaType() {
        return new VrkpaType();
    }

    /**
     * Create an instance of {@link UrfType }
     * 
     */
    public UrfType createUrfType() {
        return new UrfType();
    }

    /**
     * Create an instance of {@link VrkType }
     * 
     */
    public VrkType createVrkType() {
        return new VrkType();
    }

    /**
     * Create an instance of {@link IdlpType }
     * 
     */
    public IdlpType createIdlpType() {
        return new IdlpType();
    }

    /**
     * Create an instance of {@link UotType }
     * 
     */
    public UotType createUotType() {
        return new UotType();
    }

    /**
     * Create an instance of {@link UrsszType }
     * 
     */
    public UrsszType createUrsszType() {
        return new UrsszType();
    }

    /**
     * Create an instance of {@link IdlType }
     * 
     */
    public IdlType createIdlType() {
        return new IdlType();
    }

    /**
     * Create an instance of {@link ChpnType }
     * 
     */
    public ChpnType createChpnType() {
        return new ChpnType();
    }

    /**
     * Create an instance of {@link KolizeVType }
     * 
     */
    public KolizeVType createKolizeVType() {
        return new KolizeVType();
    }

    /**
     * Create an instance of {@link LekType }
     * 
     */
    public LekType createLekType() {
        return new LekType();
    }

    /**
     * Create an instance of {@link VrsType }
     * 
     */
    public VrsType createVrsType() {
        return new VrsType();
    }

    /**
     * Create an instance of {@link VrbType }
     * 
     */
    public VrbType createVrbType() {
        return new VrbType();
    }

    /**
     * Create an instance of {@link KuZLabType }
     * 
     */
    public KuZLabType createKuZLabType() {
        return new KuZLabType();
    }

    /**
     * Create an instance of {@link LodType }
     * 
     */
    public LodType createLodType() {
        return new LodType();
    }

    /**
     * Create an instance of {@link VrrType }
     * 
     */
    public VrrType createVrrType() {
        return new VrrType();
    }

    /**
     * Create an instance of {@link LegVykType }
     * 
     */
    public LegVykType createLegVykType() {
        return new LegVykType();
    }

    /**
     * Create an instance of {@link ZumType }
     * 
     */
    public ZumType createZumType() {
        return new ZumType();
    }

    /**
     * Create an instance of {@link UtmType }
     * 
     */
    public UtmType createUtmType() {
        return new UtmType();
    }

    /**
     * Create an instance of {@link SkalaType }
     * 
     */
    public SkalaType createSkalaType() {
        return new SkalaType();
    }

    /**
     * Create an instance of {@link NejistotaType }
     * 
     */
    public NejistotaType createNejistotaType() {
        return new NejistotaType();
    }

    /**
     * Create an instance of {@link LoprType }
     * 
     */
    public LoprType createLoprType() {
        return new LoprType();
    }

    /**
     * Create an instance of {@link RdgLokalType }
     * 
     */
    public RdgLokalType createRdgLokalType() {
        return new RdgLokalType();
    }

    /**
     * Create an instance of {@link PracovnikType }
     * 
     */
    public PracovnikType createPracovnikType() {
        return new PracovnikType();
    }

    /**
     * Create an instance of {@link PvType }
     * 
     */
    public PvType createPvType() {
        return new PvType();
    }

    /**
     * Create an instance of {@link VroType }
     * 
     */
    public VroType createVroType() {
        return new VroType();
    }

    /**
     * Create an instance of {@link VrzType }
     * 
     */
    public VrzType createVrzType() {
        return new VrzType();
    }

    /**
     * Create an instance of {@link KuZType }
     * 
     */
    public KuZType createKuZType() {
        return new KuZType();
    }

    /**
     * Create an instance of {@link HspType }
     * 
     */
    public HspType createHspType() {
        return new HspType();
    }

    /**
     * Create an instance of {@link Ptext }
     * 
     */
    public Ptext createPtext() {
        return new Ptext();
    }

    /**
     * Create an instance of {@link DavkaType }
     * 
     */
    public DavkaType createDavkaType() {
        return new DavkaType();
    }

    /**
     * Create an instance of {@link AuzType }
     * 
     */
    public AuzType createAuzType() {
        return new AuzType();
    }

    /**
     * Create an instance of {@link UaType }
     * 
     */
    public UaType createUaType() {
        return new UaType();
    }

    /**
     * Create an instance of {@link KuOType }
     * 
     */
    public KuOType createKuOType() {
        return new KuOType();
    }

    /**
     * Create an instance of {@link VrxType }
     * 
     */
    public VrxType createVrxType() {
        return new VrxType();
    }

    /**
     * Create an instance of {@link LoiType }
     * 
     */
    public LoiType createLoiType() {
        return new LoiType();
    }

    /**
     * Create an instance of {@link UType }
     * 
     */
    public UType createUType() {
        return new UType();
    }

    /**
     * Create an instance of {@link ZpshlType }
     * 
     */
    public ZpshlType createZpshlType() {
        return new ZpshlType();
    }

    /**
     * Create an instance of {@link DavkaType.Reakce }
     * 
     */
    public DavkaType.Reakce createDavkaTypeReakce() {
        return new DavkaType.Reakce();
    }

    /**
     * Create an instance of {@link VchzType }
     * 
     */
    public VchzType createVchzType() {
        return new VchzType();
    }

    /**
     * Create an instance of {@link KvantitaType }
     * 
     */
    public KvantitaType createKvantitaType() {
        return new KvantitaType();
    }

    /**
     * Create an instance of {@link Ip }
     * 
     */
    public Ip createIp() {
        return new Ip();
    }

    /**
     * Create an instance of {@link ChybaPdType }
     * 
     */
    public ChybaPdType createChybaPdType() {
        return new ChybaPdType();
    }

    /**
     * Create an instance of {@link LeType.Lez }
     * 
     */
    public LeType.Lez createLeTypeLez() {
        return new LeType.Lez();
    }

}
