//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatXxType;


/**
 * <p>Java class for oczType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oczType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="davka" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}davkaType" maxOccurs="unbounded"/>
 *         &lt;element name="dat_po" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *         &lt;element name="pozn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
 *         &lt;element name="oczAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typ_oc_kod" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="typ_oc_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oczType", propOrder = {
    "davka",
    "datPo",
    "pozn",
    "oczAny"
})
public class OczType {

    @XmlElement(required = true)
    protected List<DavkaType> davka;
    @XmlElement(name = "dat_po")
    protected DatXxType datPo;
    protected String pozn;
    protected AnyType oczAny;
    @XmlAttribute(name = "typ_oc_kod")
    protected String typOcKod;
    @XmlAttribute(name = "typ_oc_text")
    protected String typOcText;

    /**
     * Gets the value of the davka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the davka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDavka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DavkaType }
     * 
     * 
     */
    public List<DavkaType> getDavka() {
        if (davka == null) {
            davka = new ArrayList<DavkaType>();
        }
        return this.davka;
    }

    /**
     * Gets the value of the datPo property.
     * 
     * @return
     *     possible object is
     *     {@link DatXxType }
     *     
     */
    public DatXxType getDatPo() {
        return datPo;
    }

    /**
     * Sets the value of the datPo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatXxType }
     *     
     */
    public void setDatPo(DatXxType value) {
        this.datPo = value;
    }

    /**
     * Gets the value of the pozn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPozn() {
        return pozn;
    }

    /**
     * Sets the value of the pozn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPozn(String value) {
        this.pozn = value;
    }

    /**
     * Gets the value of the oczAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getOczAny() {
        return oczAny;
    }

    /**
     * Sets the value of the oczAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setOczAny(AnyType value) {
        this.oczAny = value;
    }

    /**
     * Gets the value of the typOcKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypOcKod() {
        return typOcKod;
    }

    /**
     * Sets the value of the typOcKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypOcKod(String value) {
        this.typOcKod = value;
    }

    /**
     * Gets the value of the typOcText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypOcText() {
        return typOcText;
    }

    /**
     * Sets the value of the typOcText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypOcText(String value) {
        this.typOcText = value;
    }

}
