//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pece_zmType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pece_zmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dath_zm" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType"/>
 *         &lt;element name="idl" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}idlType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ind_p_pzt" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ind_p_pdn" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pece_zmType", propOrder = {
    "dathZm",
    "idl"
})
public class PeceZmType {

    @XmlElement(name = "dath_zm", required = true)
    protected DathXxType dathZm;
    protected IdlType idl;
    @XmlAttribute(name = "ind_p_pzt", required = true)
    protected String indPPzt;
    @XmlAttribute(name = "ind_p_pdn", required = true)
    protected String indPPdn;

    /**
     * Gets the value of the dathZm property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathZm() {
        return dathZm;
    }

    /**
     * Sets the value of the dathZm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathZm(DathXxType value) {
        this.dathZm = value;
    }

    /**
     * Gets the value of the idl property.
     * 
     * @return
     *     possible object is
     *     {@link IdlType }
     *     
     */
    public IdlType getIdl() {
        return idl;
    }

    /**
     * Sets the value of the idl property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdlType }
     *     
     */
    public void setIdl(IdlType value) {
        this.idl = value;
    }

    /**
     * Gets the value of the indPPzt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndPPzt() {
        return indPPzt;
    }

    /**
     * Sets the value of the indPPzt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndPPzt(String value) {
        this.indPPzt = value;
    }

    /**
     * Gets the value of the indPPdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndPPdn() {
        return indPPdn;
    }

    /**
     * Sets the value of the indPPdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndPPdn(String value) {
        this.indPPdn = value;
    }

}
