//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import mzcr.cz.ns.dasta.ds4.ds_dasta.AType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.TypPvType;


/**
 * <p>Java class for pvType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pvType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="p" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}pType"/>
 *           &lt;element ref="{urn:cz-mzcr:ns:dasta:ds4:ds_dasta}a" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="pvAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dat_ab" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="typ_pv" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}typ_pvType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pvType", propOrder = {
    "p",
    "a",
    "pvAny"
})
public class PvType {

    protected PType p;
    @XmlElement(namespace = "urn:cz-mzcr:ns:dasta:ds4:ds_dasta")
    protected AType a;
    protected AnyType pvAny;
    @XmlAttribute(name = "dat_ab")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datAb;
    @XmlAttribute(name = "typ_pv", required = true)
    protected TypPvType typPv;

    /**
     * Gets the value of the p property.
     * 
     * @return
     *     possible object is
     *     {@link PType }
     *     
     */
    public PType getP() {
        return p;
    }

    /**
     * Sets the value of the p property.
     * 
     * @param value
     *     allowed object is
     *     {@link PType }
     *     
     */
    public void setP(PType value) {
        this.p = value;
    }

    /**
     * Gets the value of the a property.
     * 
     * @return
     *     possible object is
     *     {@link AType }
     *     
     */
    public AType getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     * @param value
     *     allowed object is
     *     {@link AType }
     *     
     */
    public void setA(AType value) {
        this.a = value;
    }

    /**
     * Gets the value of the pvAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getPvAny() {
        return pvAny;
    }

    /**
     * Sets the value of the pvAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setPvAny(AnyType value) {
        this.pvAny = value;
    }

    /**
     * Gets the value of the datAb property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatAb() {
        return datAb;
    }

    /**
     * Sets the value of the datAb property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatAb(XMLGregorianCalendar value) {
        this.datAb = value;
    }

    /**
     * Gets the value of the typPv property.
     * 
     * @return
     *     possible object is
     *     {@link TypPvType }
     *     
     */
    public TypPvType getTypPv() {
        return typPv;
    }

    /**
     * Sets the value of the typPv property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypPvType }
     *     
     */
    public void setTypPv(TypPvType value) {
        this.typPv = value;
    }

}
