//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_cistype.NCLPUVIS;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for skalaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="skalaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="s1" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" minOccurs="0"/>
 *         &lt;element name="s2" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" minOccurs="0"/>
 *         &lt;element name="s3" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" minOccurs="0"/>
 *         &lt;element name="s4" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2"/>
 *         &lt;element name="s5" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2"/>
 *         &lt;element name="s6" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" minOccurs="0"/>
 *         &lt;element name="s7" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" minOccurs="0"/>
 *         &lt;element name="s8" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number6.2" minOccurs="0"/>
 *         &lt;element name="interpret_g_z" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str35" minOccurs="0"/>
 *         &lt;element name="skalaAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="atribut" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}multi8LVVISA" />
 *       &lt;attribute name="udalost" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}NCLPUVIS" />
 *       &lt;attribute name="algoritmus" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="s_hodn_o" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}sHodnotaType" />
 *       &lt;attribute name="t_hodn_o" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}tHodnotaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "skalaType", propOrder = {
    "s1",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "interpretGZ",
    "skalaAny"
})
public class SkalaType {

    protected String s1;
    protected String s2;
    protected String s3;
    @XmlElement(required = true)
    protected String s4;
    @XmlElement(required = true)
    protected String s5;
    protected String s6;
    protected String s7;
    protected String s8;
    @XmlElement(name = "interpret_g_z")
    protected String interpretGZ;
    protected AnyType skalaAny;
    @XmlAttribute
    protected String atribut;
    @XmlAttribute
    protected NCLPUVIS udalost;
    @XmlAttribute
    protected String algoritmus;
    @XmlAttribute(name = "s_hodn_o")
    protected Integer sHodnO;
    @XmlAttribute(name = "t_hodn_o")
    protected Integer tHodnO;

    /**
     * Gets the value of the s1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS1() {
        return s1;
    }

    /**
     * Sets the value of the s1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS1(String value) {
        this.s1 = value;
    }

    /**
     * Gets the value of the s2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS2() {
        return s2;
    }

    /**
     * Sets the value of the s2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS2(String value) {
        this.s2 = value;
    }

    /**
     * Gets the value of the s3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS3() {
        return s3;
    }

    /**
     * Sets the value of the s3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS3(String value) {
        this.s3 = value;
    }

    /**
     * Gets the value of the s4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS4() {
        return s4;
    }

    /**
     * Sets the value of the s4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS4(String value) {
        this.s4 = value;
    }

    /**
     * Gets the value of the s5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS5() {
        return s5;
    }

    /**
     * Sets the value of the s5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS5(String value) {
        this.s5 = value;
    }

    /**
     * Gets the value of the s6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS6() {
        return s6;
    }

    /**
     * Sets the value of the s6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS6(String value) {
        this.s6 = value;
    }

    /**
     * Gets the value of the s7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS7() {
        return s7;
    }

    /**
     * Sets the value of the s7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS7(String value) {
        this.s7 = value;
    }

    /**
     * Gets the value of the s8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS8() {
        return s8;
    }

    /**
     * Sets the value of the s8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS8(String value) {
        this.s8 = value;
    }

    /**
     * Gets the value of the interpretGZ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretGZ() {
        return interpretGZ;
    }

    /**
     * Sets the value of the interpretGZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretGZ(String value) {
        this.interpretGZ = value;
    }

    /**
     * Gets the value of the skalaAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getSkalaAny() {
        return skalaAny;
    }

    /**
     * Sets the value of the skalaAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setSkalaAny(AnyType value) {
        this.skalaAny = value;
    }

    /**
     * Gets the value of the atribut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtribut() {
        return atribut;
    }

    /**
     * Sets the value of the atribut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtribut(String value) {
        this.atribut = value;
    }

    /**
     * Gets the value of the udalost property.
     * 
     * @return
     *     possible object is
     *     {@link NCLPUVIS }
     *     
     */
    public NCLPUVIS getUdalost() {
        return udalost;
    }

    /**
     * Sets the value of the udalost property.
     * 
     * @param value
     *     allowed object is
     *     {@link NCLPUVIS }
     *     
     */
    public void setUdalost(NCLPUVIS value) {
        this.udalost = value;
    }

    /**
     * Gets the value of the algoritmus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlgoritmus() {
        return algoritmus;
    }

    /**
     * Sets the value of the algoritmus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlgoritmus(String value) {
        this.algoritmus = value;
    }

    /**
     * Gets the value of the sHodnO property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSHodnO() {
        return sHodnO;
    }

    /**
     * Sets the value of the sHodnO property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSHodnO(Integer value) {
        this.sHodnO = value;
    }

    /**
     * Gets the value of the tHodnO property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTHodnO() {
        return tHodnO;
    }

    /**
     * Sets the value of the tHodnO property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTHodnO(Integer value) {
        this.tHodnO = value;
    }

}
