//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;
import mzcr.cz.ns.dasta.ds4.ds_type.AutorType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatDuType;
import mzcr.cz.ns.dasta.ds4.ds_type.DatXxType;


/**
 * <p>Java class for urfType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="urfType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="u_rf" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255"/>
 *         &lt;element name="autor" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}autorType" minOccurs="0"/>
 *         &lt;element name="dat_du" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_duType" minOccurs="0"/>
 *         &lt;element name="dat_ak" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}dat_xxType" minOccurs="0"/>
 *         &lt;element name="urfAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dat_ab" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="ind_oprav_sd" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}indOprSdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "urfType", propOrder = {
    "uRf",
    "autor",
    "datDu",
    "datAk",
    "urfAny"
})
public class UrfType {

    @XmlElement(name = "u_rf", required = true)
    protected String uRf;
    protected AutorType autor;
    @XmlElement(name = "dat_du")
    protected DatDuType datDu;
    @XmlElement(name = "dat_ak")
    protected DatXxType datAk;
    protected AnyType urfAny;
    @XmlAttribute(name = "dat_ab")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datAb;
    @XmlAttribute(name = "ind_oprav_sd", required = true)
    protected String indOpravSd;

    /**
     * Gets the value of the uRf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURf() {
        return uRf;
    }

    /**
     * Sets the value of the uRf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURf(String value) {
        this.uRf = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link AutorType }
     *     
     */
    public AutorType getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutorType }
     *     
     */
    public void setAutor(AutorType value) {
        this.autor = value;
    }

    /**
     * Gets the value of the datDu property.
     * 
     * @return
     *     possible object is
     *     {@link DatDuType }
     *     
     */
    public DatDuType getDatDu() {
        return datDu;
    }

    /**
     * Sets the value of the datDu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatDuType }
     *     
     */
    public void setDatDu(DatDuType value) {
        this.datDu = value;
    }

    /**
     * Gets the value of the datAk property.
     * 
     * @return
     *     possible object is
     *     {@link DatXxType }
     *     
     */
    public DatXxType getDatAk() {
        return datAk;
    }

    /**
     * Sets the value of the datAk property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatXxType }
     *     
     */
    public void setDatAk(DatXxType value) {
        this.datAk = value;
    }

    /**
     * Gets the value of the urfAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getUrfAny() {
        return urfAny;
    }

    /**
     * Sets the value of the urfAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setUrfAny(AnyType value) {
        this.urfAny = value;
    }

    /**
     * Gets the value of the datAb property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatAb() {
        return datAb;
    }

    /**
     * Sets the value of the datAb property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatAb(XMLGregorianCalendar value) {
        this.datAb = value;
    }

    /**
     * Gets the value of the indOpravSd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndOpravSd() {
        return indOpravSd;
    }

    /**
     * Sets the value of the indOpravSd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndOpravSd(String value) {
        this.indOpravSd = value;
    }

}
