//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ursszType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ursszType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dath_uk" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ssz_kod" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str3" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ursszType", propOrder = {
    "dathUk"
})
public class UrsszType {

    @XmlElement(name = "dath_uk", required = true)
    protected DathXxType dathUk;
    @XmlAttribute(name = "ssz_kod", required = true)
    protected String sszKod;

    /**
     * Gets the value of the dathUk property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathUk() {
        return dathUk;
    }

    /**
     * Sets the value of the dathUk property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathUk(DathXxType value) {
        this.dathUk = value;
    }

    /**
     * Gets the value of the sszKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSszKod() {
        return sszKod;
    }

    /**
     * Sets the value of the sszKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSszKod(String value) {
        this.sszKod = value;
    }

}
