//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vchzType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vchzType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dath_od" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}dath_xxType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="vch1_od" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8e" />
 *       &lt;attribute name="vch1_do" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8e" />
 *       &lt;attribute name="vch2_od" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8e" />
 *       &lt;attribute name="vch2_do" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8e" />
 *       &lt;attribute name="ind_vch_pvl">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ind_vch_zrs">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vchzType", propOrder = {
    "dathOd"
})
public class VchzType {

    @XmlElement(name = "dath_od", required = true)
    protected DathXxType dathOd;
    @XmlAttribute(name = "vch1_od")
    protected String vch1Od;
    @XmlAttribute(name = "vch1_do")
    protected String vch1Do;
    @XmlAttribute(name = "vch2_od")
    protected String vch2Od;
    @XmlAttribute(name = "vch2_do")
    protected String vch2Do;
    @XmlAttribute(name = "ind_vch_pvl")
    protected String indVchPvl;
    @XmlAttribute(name = "ind_vch_zrs")
    protected String indVchZrs;

    /**
     * Gets the value of the dathOd property.
     * 
     * @return
     *     possible object is
     *     {@link DathXxType }
     *     
     */
    public DathXxType getDathOd() {
        return dathOd;
    }

    /**
     * Sets the value of the dathOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DathXxType }
     *     
     */
    public void setDathOd(DathXxType value) {
        this.dathOd = value;
    }

    /**
     * Gets the value of the vch1Od property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVch1Od() {
        return vch1Od;
    }

    /**
     * Sets the value of the vch1Od property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVch1Od(String value) {
        this.vch1Od = value;
    }

    /**
     * Gets the value of the vch1Do property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVch1Do() {
        return vch1Do;
    }

    /**
     * Sets the value of the vch1Do property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVch1Do(String value) {
        this.vch1Do = value;
    }

    /**
     * Gets the value of the vch2Od property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVch2Od() {
        return vch2Od;
    }

    /**
     * Sets the value of the vch2Od property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVch2Od(String value) {
        this.vch2Od = value;
    }

    /**
     * Gets the value of the vch2Do property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVch2Do() {
        return vch2Do;
    }

    /**
     * Sets the value of the vch2Do property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVch2Do(String value) {
        this.vch2Do = value;
    }

    /**
     * Gets the value of the indVchPvl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndVchPvl() {
        return indVchPvl;
    }

    /**
     * Sets the value of the indVchPvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndVchPvl(String value) {
        this.indVchPvl = value;
    }

    /**
     * Gets the value of the indVchZrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndVchZrs() {
        return indVchZrs;
    }

    /**
     * Sets the value of the indVchZrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndVchZrs(String value) {
        this.indVchZrs = value;
    }

}
