//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for vrbType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vrbType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nazvy" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}nazvyType" minOccurs="0"/>
 *         &lt;element name="text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}textType"/>
 *         &lt;element name="vrbAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typ_vzniku" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}typVznikuType" />
 *       &lt;attribute name="misto_vzniku" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}mistoVznikuType" />
 *       &lt;attribute name="autorizace" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}logicalA" />
 *       &lt;attribute name="specifikace" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vrbType", propOrder = {
    "nazvy",
    "text",
    "vrbAny"
})
public class VrbType {

    protected NazvyType nazvy;
    @XmlElement(required = true)
    protected TextType text;
    protected AnyType vrbAny;
    @XmlAttribute(name = "typ_vzniku", required = true)
    protected String typVzniku;
    @XmlAttribute(name = "misto_vzniku", required = true)
    protected String mistoVzniku;
    @XmlAttribute(required = true)
    protected String autorizace;
    @XmlAttribute
    protected String specifikace;

    /**
     * Gets the value of the nazvy property.
     * 
     * @return
     *     possible object is
     *     {@link NazvyType }
     *     
     */
    public NazvyType getNazvy() {
        return nazvy;
    }

    /**
     * Sets the value of the nazvy property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazvyType }
     *     
     */
    public void setNazvy(NazvyType value) {
        this.nazvy = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setText(TextType value) {
        this.text = value;
    }

    /**
     * Gets the value of the vrbAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getVrbAny() {
        return vrbAny;
    }

    /**
     * Sets the value of the vrbAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setVrbAny(AnyType value) {
        this.vrbAny = value;
    }

    /**
     * Gets the value of the typVzniku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypVzniku() {
        return typVzniku;
    }

    /**
     * Sets the value of the typVzniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypVzniku(String value) {
        this.typVzniku = value;
    }

    /**
     * Gets the value of the mistoVzniku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMistoVzniku() {
        return mistoVzniku;
    }

    /**
     * Sets the value of the mistoVzniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMistoVzniku(String value) {
        this.mistoVzniku = value;
    }

    /**
     * Gets the value of the autorizace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutorizace() {
        return autorizace;
    }

    /**
     * Sets the value of the autorizace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutorizace(String value) {
        this.autorizace = value;
    }

    /**
     * Gets the value of the specifikace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifikace() {
        return specifikace;
    }

    /**
     * Sets the value of the specifikace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifikace(String value) {
        this.specifikace = value;
    }

}
