//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_cistype.NCMPAGV;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for vrkpaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vrkpaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kvantita" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}kvantitaType" minOccurs="0"/>
 *         &lt;element name="vrav" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vravAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="vl_kod" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}NCMPAGV" />
 *                 &lt;attribute name="vl_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *                 &lt;attribute name="pritomnost" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LMHPUVN" />
 *                 &lt;attribute name="dodatek" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vrac" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="kvantita" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}kvantitaType" minOccurs="0"/>
 *                   &lt;element name="vracAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="latka_kod" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *                 &lt;attribute name="latka_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *                 &lt;attribute name="hod_citlivosti" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LMHCN" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="doruceni" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
 *         &lt;element name="vrmahn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
 *         &lt;element name="vrmlpn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
 *         &lt;element name="vrmzhl" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
 *         &lt;element name="vrkpaAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="agens_kod" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="agens_text" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *       &lt;attribute name="dalsi_vys" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LMIDVAN" />
 *       &lt;attribute name="pritomnost" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LMIPAN" />
 *       &lt;attribute name="druh_veliciny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str32" />
 *       &lt;attribute name="jednotka" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str20" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vrkpaType", propOrder = {
    "kvantita",
    "vrav",
    "vrac",
    "doruceni",
    "vrmahn",
    "vrmlpn",
    "vrmzhl",
    "vrkpaAny"
})
public class VrkpaType {

    protected KvantitaType kvantita;
    protected List<VrkpaType.Vrav> vrav;
    protected List<VrkpaType.Vrac> vrac;
    protected String doruceni;
    protected String vrmahn;
    protected String vrmlpn;
    protected String vrmzhl;
    protected AnyType vrkpaAny;
    @XmlAttribute(name = "agens_kod", required = true)
    protected String agensKod;
    @XmlAttribute(name = "agens_text", required = true)
    protected String agensText;
    @XmlAttribute(name = "dalsi_vys", required = true)
    protected String dalsiVys;
    @XmlAttribute(required = true)
    protected String pritomnost;
    @XmlAttribute(name = "druh_veliciny")
    protected String druhVeliciny;
    @XmlAttribute
    protected String jednotka;

    /**
     * Gets the value of the kvantita property.
     * 
     * @return
     *     possible object is
     *     {@link KvantitaType }
     *     
     */
    public KvantitaType getKvantita() {
        return kvantita;
    }

    /**
     * Sets the value of the kvantita property.
     * 
     * @param value
     *     allowed object is
     *     {@link KvantitaType }
     *     
     */
    public void setKvantita(KvantitaType value) {
        this.kvantita = value;
    }

    /**
     * Gets the value of the vrav property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vrav property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVrav().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VrkpaType.Vrav }
     * 
     * 
     */
    public List<VrkpaType.Vrav> getVrav() {
        if (vrav == null) {
            vrav = new ArrayList<VrkpaType.Vrav>();
        }
        return this.vrav;
    }

    /**
     * Gets the value of the vrac property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vrac property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVrac().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VrkpaType.Vrac }
     * 
     * 
     */
    public List<VrkpaType.Vrac> getVrac() {
        if (vrac == null) {
            vrac = new ArrayList<VrkpaType.Vrac>();
        }
        return this.vrac;
    }

    /**
     * Gets the value of the doruceni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoruceni() {
        return doruceni;
    }

    /**
     * Sets the value of the doruceni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoruceni(String value) {
        this.doruceni = value;
    }

    /**
     * Gets the value of the vrmahn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrmahn() {
        return vrmahn;
    }

    /**
     * Sets the value of the vrmahn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrmahn(String value) {
        this.vrmahn = value;
    }

    /**
     * Gets the value of the vrmlpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrmlpn() {
        return vrmlpn;
    }

    /**
     * Sets the value of the vrmlpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrmlpn(String value) {
        this.vrmlpn = value;
    }

    /**
     * Gets the value of the vrmzhl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrmzhl() {
        return vrmzhl;
    }

    /**
     * Sets the value of the vrmzhl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrmzhl(String value) {
        this.vrmzhl = value;
    }

    /**
     * Gets the value of the vrkpaAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getVrkpaAny() {
        return vrkpaAny;
    }

    /**
     * Sets the value of the vrkpaAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setVrkpaAny(AnyType value) {
        this.vrkpaAny = value;
    }

    /**
     * Gets the value of the agensKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgensKod() {
        return agensKod;
    }

    /**
     * Sets the value of the agensKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgensKod(String value) {
        this.agensKod = value;
    }

    /**
     * Gets the value of the agensText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgensText() {
        return agensText;
    }

    /**
     * Sets the value of the agensText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgensText(String value) {
        this.agensText = value;
    }

    /**
     * Gets the value of the dalsiVys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDalsiVys() {
        return dalsiVys;
    }

    /**
     * Sets the value of the dalsiVys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDalsiVys(String value) {
        this.dalsiVys = value;
    }

    /**
     * Gets the value of the pritomnost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPritomnost() {
        return pritomnost;
    }

    /**
     * Sets the value of the pritomnost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPritomnost(String value) {
        this.pritomnost = value;
    }

    /**
     * Gets the value of the druhVeliciny property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDruhVeliciny() {
        return druhVeliciny;
    }

    /**
     * Sets the value of the druhVeliciny property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDruhVeliciny(String value) {
        this.druhVeliciny = value;
    }

    /**
     * Gets the value of the jednotka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJednotka() {
        return jednotka;
    }

    /**
     * Sets the value of the jednotka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJednotka(String value) {
        this.jednotka = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="kvantita" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}kvantitaType" minOccurs="0"/>
     *         &lt;element name="vracAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="latka_kod" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
     *       &lt;attribute name="latka_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
     *       &lt;attribute name="hod_citlivosti" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LMHCN" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kvantita",
        "vracAny"
    })
    public static class Vrac {

        protected KvantitaType kvantita;
        protected AnyType vracAny;
        @XmlAttribute(name = "latka_kod", required = true)
        protected String latkaKod;
        @XmlAttribute(name = "latka_text")
        protected String latkaText;
        @XmlAttribute(name = "hod_citlivosti", required = true)
        protected String hodCitlivosti;

        /**
         * Gets the value of the kvantita property.
         * 
         * @return
         *     possible object is
         *     {@link KvantitaType }
         *     
         */
        public KvantitaType getKvantita() {
            return kvantita;
        }

        /**
         * Sets the value of the kvantita property.
         * 
         * @param value
         *     allowed object is
         *     {@link KvantitaType }
         *     
         */
        public void setKvantita(KvantitaType value) {
            this.kvantita = value;
        }

        /**
         * Gets the value of the vracAny property.
         * 
         * @return
         *     possible object is
         *     {@link AnyType }
         *     
         */
        public AnyType getVracAny() {
            return vracAny;
        }

        /**
         * Sets the value of the vracAny property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyType }
         *     
         */
        public void setVracAny(AnyType value) {
            this.vracAny = value;
        }

        /**
         * Gets the value of the latkaKod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLatkaKod() {
            return latkaKod;
        }

        /**
         * Sets the value of the latkaKod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLatkaKod(String value) {
            this.latkaKod = value;
        }

        /**
         * Gets the value of the latkaText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLatkaText() {
            return latkaText;
        }

        /**
         * Sets the value of the latkaText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLatkaText(String value) {
            this.latkaText = value;
        }

        /**
         * Gets the value of the hodCitlivosti property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHodCitlivosti() {
            return hodCitlivosti;
        }

        /**
         * Sets the value of the hodCitlivosti property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHodCitlivosti(String value) {
            this.hodCitlivosti = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vravAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="vl_kod" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}NCMPAGV" />
     *       &lt;attribute name="vl_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
     *       &lt;attribute name="pritomnost" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LMHPUVN" />
     *       &lt;attribute name="dodatek" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vravAny"
    })
    public static class Vrav {

        protected AnyType vravAny;
        @XmlAttribute(name = "vl_kod", required = true)
        protected NCMPAGV vlKod;
        @XmlAttribute(name = "vl_text")
        protected String vlText;
        @XmlAttribute(required = true)
        protected String pritomnost;
        @XmlAttribute
        protected String dodatek;

        /**
         * Gets the value of the vravAny property.
         * 
         * @return
         *     possible object is
         *     {@link AnyType }
         *     
         */
        public AnyType getVravAny() {
            return vravAny;
        }

        /**
         * Sets the value of the vravAny property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyType }
         *     
         */
        public void setVravAny(AnyType value) {
            this.vravAny = value;
        }

        /**
         * Gets the value of the vlKod property.
         * 
         * @return
         *     possible object is
         *     {@link NCMPAGV }
         *     
         */
        public NCMPAGV getVlKod() {
            return vlKod;
        }

        /**
         * Sets the value of the vlKod property.
         * 
         * @param value
         *     allowed object is
         *     {@link NCMPAGV }
         *     
         */
        public void setVlKod(NCMPAGV value) {
            this.vlKod = value;
        }

        /**
         * Gets the value of the vlText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVlText() {
            return vlText;
        }

        /**
         * Sets the value of the vlText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVlText(String value) {
            this.vlText = value;
        }

        /**
         * Gets the value of the pritomnost property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPritomnost() {
            return pritomnost;
        }

        /**
         * Sets the value of the pritomnost property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPritomnost(String value) {
            this.pritomnost = value;
        }

        /**
         * Gets the value of the dodatek property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDodatek() {
            return dodatek;
        }

        /**
         * Sets the value of the dodatek property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDodatek(String value) {
            this.dodatek = value;
        }

    }

}
