//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_cistype.NCMPSTM;
import mzcr.cz.ns.dasta.ds4.ds_cistype.NCMPZZM;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for vrkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vrkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nazvy" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}nazvyType" minOccurs="0"/>
 *         &lt;element name="lopok" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}lopokType" maxOccurs="unbounded"/>
 *         &lt;element name="vrmmn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" maxOccurs="unbounded"/>
 *         &lt;element name="vrkpa" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}vrkpaType" maxOccurs="unbounded"/>
 *         &lt;element name="vrmahn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
 *         &lt;element name="vrmlpn" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
 *         &lt;element name="vrmzhl" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str255" minOccurs="0"/>
 *         &lt;element name="vrkAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="spec_kod" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="spec_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *       &lt;attribute name="subspec_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *       &lt;attribute name="ziskmat_kod" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}NCMPZZM" />
 *       &lt;attribute name="ziskmat_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str55" />
 *       &lt;attribute name="stav_mat" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}NCMPSTM" />
 *       &lt;attribute name="stav_zprac" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LMSZMMN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vrkType", propOrder = {
    "nazvy",
    "lopok",
    "vrmmn",
    "vrkpa",
    "vrmahn",
    "vrmlpn",
    "vrmzhl",
    "vrkAny"
})
public class VrkType {

    protected NazvyType nazvy;
    @XmlElement(required = true)
    protected List<LopokType> lopok;
    @XmlElement(required = true)
    protected List<String> vrmmn;
    @XmlElement(required = true)
    protected List<VrkpaType> vrkpa;
    protected String vrmahn;
    protected String vrmlpn;
    protected String vrmzhl;
    protected AnyType vrkAny;
    @XmlAttribute(name = "spec_kod")
    protected String specKod;
    @XmlAttribute(name = "spec_text")
    protected String specText;
    @XmlAttribute(name = "subspec_text")
    protected String subspecText;
    @XmlAttribute(name = "ziskmat_kod")
    protected NCMPZZM ziskmatKod;
    @XmlAttribute(name = "ziskmat_text")
    protected String ziskmatText;
    @XmlAttribute(name = "stav_mat")
    protected NCMPSTM stavMat;
    @XmlAttribute(name = "stav_zprac", required = true)
    protected String stavZprac;

    /**
     * Gets the value of the nazvy property.
     * 
     * @return
     *     possible object is
     *     {@link NazvyType }
     *     
     */
    public NazvyType getNazvy() {
        return nazvy;
    }

    /**
     * Sets the value of the nazvy property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazvyType }
     *     
     */
    public void setNazvy(NazvyType value) {
        this.nazvy = value;
    }

    /**
     * Gets the value of the lopok property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lopok property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLopok().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LopokType }
     * 
     * 
     */
    public List<LopokType> getLopok() {
        if (lopok == null) {
            lopok = new ArrayList<LopokType>();
        }
        return this.lopok;
    }

    /**
     * Gets the value of the vrmmn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vrmmn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVrmmn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVrmmn() {
        if (vrmmn == null) {
            vrmmn = new ArrayList<String>();
        }
        return this.vrmmn;
    }

    /**
     * Gets the value of the vrkpa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vrkpa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVrkpa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VrkpaType }
     * 
     * 
     */
    public List<VrkpaType> getVrkpa() {
        if (vrkpa == null) {
            vrkpa = new ArrayList<VrkpaType>();
        }
        return this.vrkpa;
    }

    /**
     * Gets the value of the vrmahn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrmahn() {
        return vrmahn;
    }

    /**
     * Sets the value of the vrmahn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrmahn(String value) {
        this.vrmahn = value;
    }

    /**
     * Gets the value of the vrmlpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrmlpn() {
        return vrmlpn;
    }

    /**
     * Sets the value of the vrmlpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrmlpn(String value) {
        this.vrmlpn = value;
    }

    /**
     * Gets the value of the vrmzhl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrmzhl() {
        return vrmzhl;
    }

    /**
     * Sets the value of the vrmzhl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrmzhl(String value) {
        this.vrmzhl = value;
    }

    /**
     * Gets the value of the vrkAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getVrkAny() {
        return vrkAny;
    }

    /**
     * Sets the value of the vrkAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setVrkAny(AnyType value) {
        this.vrkAny = value;
    }

    /**
     * Gets the value of the specKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecKod() {
        return specKod;
    }

    /**
     * Sets the value of the specKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecKod(String value) {
        this.specKod = value;
    }

    /**
     * Gets the value of the specText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecText() {
        return specText;
    }

    /**
     * Sets the value of the specText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecText(String value) {
        this.specText = value;
    }

    /**
     * Gets the value of the subspecText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubspecText() {
        return subspecText;
    }

    /**
     * Sets the value of the subspecText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubspecText(String value) {
        this.subspecText = value;
    }

    /**
     * Gets the value of the ziskmatKod property.
     * 
     * @return
     *     possible object is
     *     {@link NCMPZZM }
     *     
     */
    public NCMPZZM getZiskmatKod() {
        return ziskmatKod;
    }

    /**
     * Sets the value of the ziskmatKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link NCMPZZM }
     *     
     */
    public void setZiskmatKod(NCMPZZM value) {
        this.ziskmatKod = value;
    }

    /**
     * Gets the value of the ziskmatText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZiskmatText() {
        return ziskmatText;
    }

    /**
     * Sets the value of the ziskmatText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZiskmatText(String value) {
        this.ziskmatText = value;
    }

    /**
     * Gets the value of the stavMat property.
     * 
     * @return
     *     possible object is
     *     {@link NCMPSTM }
     *     
     */
    public NCMPSTM getStavMat() {
        return stavMat;
    }

    /**
     * Sets the value of the stavMat property.
     * 
     * @param value
     *     allowed object is
     *     {@link NCMPSTM }
     *     
     */
    public void setStavMat(NCMPSTM value) {
        this.stavMat = value;
    }

    /**
     * Gets the value of the stavZprac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStavZprac() {
        return stavZprac;
    }

    /**
     * Sets the value of the stavZprac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStavZprac(String value) {
        this.stavZprac = value;
    }

}
