//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for vrrType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vrrType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_ip}textType"/>
 *         &lt;element name="vrrAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rad_zahlavi" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1" default="0" />
 *       &lt;attribute name="rad_paty" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str1" default="0" />
 *       &lt;attribute name="poc_stran" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}number2d" />
 *       &lt;attribute name="autorizace" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}logicalA" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vrrType", propOrder = {
    "text",
    "vrrAny"
})
public class VrrType {

    @XmlElement(required = true)
    protected TextType text;
    protected AnyType vrrAny;
    @XmlAttribute(name = "rad_zahlavi")
    protected String radZahlavi;
    @XmlAttribute(name = "rad_paty")
    protected String radPaty;
    @XmlAttribute(name = "poc_stran")
    protected BigInteger pocStran;
    @XmlAttribute(required = true)
    protected String autorizace;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setText(TextType value) {
        this.text = value;
    }

    /**
     * Gets the value of the vrrAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getVrrAny() {
        return vrrAny;
    }

    /**
     * Sets the value of the vrrAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setVrrAny(AnyType value) {
        this.vrrAny = value;
    }

    /**
     * Gets the value of the radZahlavi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadZahlavi() {
        if (radZahlavi == null) {
            return "0";
        } else {
            return radZahlavi;
        }
    }

    /**
     * Sets the value of the radZahlavi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadZahlavi(String value) {
        this.radZahlavi = value;
    }

    /**
     * Gets the value of the radPaty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadPaty() {
        if (radPaty == null) {
            return "0";
        } else {
            return radPaty;
        }
    }

    /**
     * Sets the value of the radPaty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadPaty(String value) {
        this.radPaty = value;
    }

    /**
     * Gets the value of the pocStran property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPocStran() {
        return pocStran;
    }

    /**
     * Sets the value of the pocStran property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPocStran(BigInteger value) {
        this.pocStran = value;
    }

    /**
     * Gets the value of the autorizace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutorizace() {
        return autorizace;
    }

    /**
     * Sets the value of the autorizace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutorizace(String value) {
        this.autorizace = value;
    }

}
