//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 07:50:19 odp. CEST 
//


package mzcr.cz.ns.dasta.ds4.ds_ip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import mzcr.cz.ns.dasta.ds4.ds_cistype.LVPHKN;
import mzcr.cz.ns.dasta.ds4.ds_type.AnyType;


/**
 * <p>Java class for vrs_hType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vrs_hType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vrshAny" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}AnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="hodnota1_klic" use="required" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="hodnota1_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str32" />
 *       &lt;attribute name="priznak2_kvant" type="{urn:cz-mzcr:ns:dasta:ds4:ds_cistype}LVPHKN" />
 *       &lt;attribute name="hodnota2_cislo" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="hodnota2_klic" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str8" />
 *       &lt;attribute name="hodnota2_text" type="{urn:cz-mzcr:ns:dasta:ds4:ds_type}str32" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vrs_hType", propOrder = {
    "vrshAny"
})
public class VrsHType {

    protected AnyType vrshAny;
    @XmlAttribute(name = "hodnota1_klic", required = true)
    protected String hodnota1Klic;
    @XmlAttribute(name = "hodnota1_text")
    protected String hodnota1Text;
    @XmlAttribute(name = "priznak2_kvant")
    protected LVPHKN priznak2Kvant;
    @XmlAttribute(name = "hodnota2_cislo")
    protected String hodnota2Cislo;
    @XmlAttribute(name = "hodnota2_klic")
    protected String hodnota2Klic;
    @XmlAttribute(name = "hodnota2_text")
    protected String hodnota2Text;

    /**
     * Gets the value of the vrshAny property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getVrshAny() {
        return vrshAny;
    }

    /**
     * Sets the value of the vrshAny property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setVrshAny(AnyType value) {
        this.vrshAny = value;
    }

    /**
     * Gets the value of the hodnota1Klic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHodnota1Klic() {
        return hodnota1Klic;
    }

    /**
     * Sets the value of the hodnota1Klic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHodnota1Klic(String value) {
        this.hodnota1Klic = value;
    }

    /**
     * Gets the value of the hodnota1Text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHodnota1Text() {
        return hodnota1Text;
    }

    /**
     * Sets the value of the hodnota1Text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHodnota1Text(String value) {
        this.hodnota1Text = value;
    }

    /**
     * Gets the value of the priznak2Kvant property.
     * 
     * @return
     *     possible object is
     *     {@link LVPHKN }
     *     
     */
    public LVPHKN getPriznak2Kvant() {
        return priznak2Kvant;
    }

    /**
     * Sets the value of the priznak2Kvant property.
     * 
     * @param value
     *     allowed object is
     *     {@link LVPHKN }
     *     
     */
    public void setPriznak2Kvant(LVPHKN value) {
        this.priznak2Kvant = value;
    }

    /**
     * Gets the value of the hodnota2Cislo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHodnota2Cislo() {
        return hodnota2Cislo;
    }

    /**
     * Sets the value of the hodnota2Cislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHodnota2Cislo(String value) {
        this.hodnota2Cislo = value;
    }

    /**
     * Gets the value of the hodnota2Klic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHodnota2Klic() {
        return hodnota2Klic;
    }

    /**
     * Sets the value of the hodnota2Klic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHodnota2Klic(String value) {
        this.hodnota2Klic = value;
    }

    /**
     * Gets the value of the hodnota2Text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHodnota2Text() {
        return hodnota2Text;
    }

    /**
     * Sets the value of the hodnota2Text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHodnota2Text(String value) {
        this.hodnota2Text = value;
    }

}
